import {esc,now} from '../utils.js';
import {validateDeck,cardProgress,nextCard,validateCardEvents} from '../domain/flashcards.js';
import {createCardStore} from '../storage/cards.js';
const sentenceSegmenter=typeof Intl.Segmenter==='function'?new Intl.Segmenter('ja',{granularity:'sentence'}):null;
const cardTitle=text=>text.split(/(?<=[？?])\s+(?=\S)/u).map(part=>`<span class="card-question">${esc(part)}</span>`).join('');
const cardMeaning=text=>(sentenceSegmenter?[...sentenceSegmenter.segment(text)].map(item=>item.segment):text.split(/(?<=[。！？])\s*/u)).map(part=>part.trim()).filter(Boolean).map(part=>`<p>${esc(part)}</p>`).join('');
export function createCardFeature({qualification,content,getStore,getNavigation,onNavigate,onUpdate,onNotice,download,rootPath}){
 let deck=null,store=null,events=[],checkpoint=null,owner=null,generation=0,busy=false;
 async function bind(){const token=++generation,previous=store,mainStore=getStore();store=null;events=[];checkpoint=null;await previous?.close();const identity=await mainStore.identity();if(token!==generation)return;owner=identity.owner;store=createCardStore({rootPath,owner,qualificationId:qualification.id});}
 async function load(){if(!store)await bind();const token=generation,target=store;const loaded=validateDeck(await content.loadFlashcards(),qualification,content.questions);const saved=await target.read();if(token!==generation)return false;deck=loaded;events=saved.events;const c=deck.cards.find(c=>c.id===saved.checkpoint?.cardId);checkpoint=c&&c.version===saved.checkpoint.cardVersion&&typeof saved.checkpoint.flipped==='boolean'&&Array.isArray(saved.checkpoint.seen)&&saved.checkpoint.seen.length<=10000&&saved.checkpoint.seen.every(id=>deck.cards.some(c=>c.id===id))&&(!saved.checkpoint.topicId||c.topicId===saved.checkpoint.topicId)&&(!saved.checkpoint.topicId||qualification.topics.some(t=>t.id===saved.checkpoint.topicId))?saved.checkpoint:nextCard(deck.cards,events);return true;}
 function html(){const card=deck?.cards.find(c=>c.id===checkpoint?.cardId),progress=cardProgress(deck?.cards||[],events);return `<div class="page-heading"><h1>単語帳</h1><button class="button study-back-button" data-view="home"><span aria-hidden="true">⌂</span> ホーム</button></div><p class="small muted">自己評価の記録 · 確認済み ${progress.seen} / ${deck?.cards.length||0}枚 · また確認 ${progress.again}枚</p><label class="card-field">分野 <select name="card-topic"><option value="">すべて</option>${qualification.topics.filter(t=>deck?.cards.some(c=>c.topicId===t.id)).map(t=>`<option value="${esc(t.id)}" ${checkpoint?.topicId===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label>${card?`<article class="panel flashcard"><p class="small muted">${esc(qualification.topics.find(t=>t.id===card.topicId)?.name||card.topicId)}</p><h2 tabindex="-1">${cardTitle(card.front)}</h2>${checkpoint.flipped?`<div class="card-back" tabindex="-1">${cardMeaning(card.back)}</div><div class="button-row card-ratings"><button class="button primary" data-action="card-rate" data-outcome="recalled">思い出せた → 次へ</button><button class="button secondary" data-action="card-rate" data-outcome="again">もう一度 → 次へ</button></div><details><summary>関連する過去問・出典</summary><p class="small muted">${esc(card.sourceNote)}</p>${card.relatedQuestionIds.map(id=>`<button class="button secondary" data-action="start" data-id="${esc(id)}">過去問で確認する</button>`).join('')}</details>`:'<p class="small muted">意味を思い出してから、裏を見ます。</p><button class="button primary card-flip" data-action="card-flip">意味を見る</button>'}</article>`:'<p class="panel">この分野のカードはまだありません。</p>'}<p class="small muted">自己評価は四択の正答率・計画の実績に含めません。単語帳の記録はこの端末の現在のアカウントと資格に保存します。クラウド同期はしません。</p><details class="card-data"><summary>単語帳の記録を保存・取り込む</summary><p class="small muted">通常の学習記録とは別のファイルです。書き出しておくと、別の端末へ移せます。</p><div class="button-row"><button class="button secondary" data-action="card-clear">単語帳の記録を削除</button><button class="button secondary" data-action="card-export">単語帳の記録を書き出す</button><label class="button secondary file-label">単語帳の記録を取り込む<input id="import-cards" type="file" accept="application/json,.json"></label></div></details>`;}
 async function action(el){const action=el.dataset.action;if(!['cards-open','card-flip','card-rate','card-export','card-clear'].includes(action))return false;if(busy)return true;busy=true;const nav=getNavigation(),token=generation,target=store;
  try{if(action==='cards-open'){if(await load()&&nav===getNavigation()){onNotice('');onNavigate('flashcards');}}
   else if(action==='card-clear'){if(!confirm('この端末・アカウント・資格の単語帳記録を削除しますか？ 四択の学習記録は保持します。'))return true;await target.clear();if(token!==generation)return true;events=[];checkpoint=nextCard(deck.cards,events);onUpdate();onNotice('単語帳の記録を削除しました。');}
   else if(action==='card-export'){const saved=await target.read();if(token!==generation)return true;download({format:'hitomon-card-record',version:1,qualificationId:qualification.id,events:saved.events},`${qualification.id}-card-record.json`);}
   else if(checkpoint){let next=structuredClone(checkpoint),event=null;if(action==='card-flip'){if(next.flipped)return true;next.flipped=true;}else if(action==='card-rate'){if(!next.flipped||!['recalled','again'].includes(el.dataset.outcome))return true;const card=deck.cards.find(c=>c.id===next.cardId);event={id:crypto.randomUUID(),cardId:card.id,cardVersion:card.version,outcome:el.dataset.outcome,at:now()};next=nextCard(deck.cards,[...events,event],{...next,seen:[...new Set([...next.seen,card.id])]});}
    await target.write(next,event);if(token!==generation||nav!==getNavigation())return true;const saved=await target.read();if(token!==generation||nav!==getNavigation())return true;events=saved.events;checkpoint=next;onNotice('');onUpdate();if(action==='card-flip')document.querySelector('.card-back')?.focus({preventScroll:true});else document.querySelector('.flashcard h2')?.focus();}
  }catch(error){onNotice(error.message+' 単語帳の保存を確認して、もう一度操作してください。');}finally{busy=false;}return true;
 }
 async function change(el){if(el.name!=='card-topic')return false;if(busy)return true;busy=true;const token=generation,target=store;try{if(el.value&&!qualification.topics.some(t=>t.id===el.value))return true;const next=nextCard(deck.cards,events,{seen:[],topicId:el.value||null});await target.write(next);if(token===generation){checkpoint=next;onNotice('');onUpdate();}}catch(error){onNotice(error.message);}finally{busy=false;}return true;}
 async function importFile(file){if(!file)return;const token=generation,target=store;if(file.size>8*1024*1024)throw new Error('単語帳の記録は8MB以下にしてください。');const data=JSON.parse(await file.text());if(data.format!=='hitomon-card-record'||data.version!==1||data.qualificationId!==qualification.id||Object.keys(data).some(k=>!['format','version','qualificationId','events'].includes(k)))throw new Error('この資格の単語帳の記録ではありません。');validateCardEvents(data.events);if(token!==generation)return;await target.importEvents(data.events);const saved=await target.read();if(token!==generation)return;events=saved.events;onUpdate();onNotice('単語帳の記録を取り込みました。');}
 return {bind,load,html,action,change,importFile};
}
