"""Frozen audit reproducer for be9287f; expected known failures, not CI acceptance tests.
Serve this repository at http://127.0.0.1:4173/. Uses isolated guests, no account.
"""
import json,shutil,sys
from pathlib import Path
from datetime import datetime,timezone
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'tests'))
from browser_storage import state,nav,write_state,open_plan_editor,open_plan_ai
BASE='http://127.0.0.1:4173/'
OUT=Path('/tmp/hitomon-spec-audit-20261008');OUT.mkdir(parents=True,exist_ok=True);results=[]
def record(id,data):results.append({'id':id,**data});print(id,json.dumps(data,ensure_ascii=False),flush=True)
READ_WORKSPACE='''async()=>{const {createLocalStore}=await import('/src/storage/local.js'),s=createLocalStore({qualificationId:'ap',rootPath:'/'});const identity=await s.identity();await s.close();const {createWorkspaceStore}=await import('/src/storage/workspace.js'),w=createWorkspaceStore({...identity,rootPath:'/',validate:(k,p)=>p});try{return await w.read();}finally{await w.close();}}'''
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),args=['--no-sandbox'])
 def fresh(path='',zone='Asia/Tokyo',clock=None):
  ctx=b.new_context(viewport={'width':390,'height':844},timezone_id=zone);pg=ctx.new_page();pg.set_default_timeout(10000);pg.on('dialog',lambda d:d.accept())
  if clock:pg.clock.install(time=clock)
  pg.goto(BASE+path);pg.locator('.study-entrance[data-paper-mode=all]').wait_for();pg.wait_for_function('document.getElementById("sync-state").textContent.includes("ログインすると、学習記録を同期できます。")');return ctx,pg
 # Failure injection: the storage transaction rejects; only this isolated guest is affected.
 ctx,pg=fresh();pg.locator('.study-entrance[data-paper-mode=paperless]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();pg.get_by_role('button',name='ヒントを1つ見る',exact=True).click();pg.get_by_role('radio').first.check();before=state(pg);aid=before['currentId']
 pg.evaluate('''()=>{const original=IDBObjectStore.prototype.put;window.__put=original;IDBObjectStore.prototype.put=function(...args){if(this.name==='outbox')throw new DOMException('audit full','QuotaExceededError');return original.apply(this,args);};}''')
 pg.get_by_role('button',name='この問題は紙ペンが必要',exact=True).click();pg.locator('.study-entrance[data-paper-mode=desk]').wait_for();pg.wait_for_function('document.getElementById("save-state").textContent==="保存できていません"');persisted=state(pg)
 assert persisted['currentId']==aid and not persisted['settings']['deskQuestionIds'];assert pg.locator('.study-entrance[data-paper-mode=desk]').get_attribute('data-id')==aid
 record('S01',{'screen':'home','persistedView':persisted['view'],'persistedCurrent':persisted['currentId'],'persistedDeskIds':persisted['settings']['deskQuestionIds'],'notice':pg.locator('#notice').inner_text(),'saveState':pg.locator('#save-state').inner_text()});pg.screenshot(path=str(OUT/'desk-save-failure.png'));ctx.close()
 # Opening an adjacent planning block rerenders the unsaved manual form.
 ctx,pg=fresh();pg.get_by_role('button',name='計画を登録',exact=True).click();open_plan_editor(pg);f=pg.locator('#context-form');f.evaluate('(el)=>el.parentElement.open=true');f.locator('[name=rationale]').fill('まだ保存していない計画の理由');pg.get_by_role('button',name='AIに相談・JSONを登録',exact=True).click();after=pg.locator('#context-form [name=rationale]').input_value();assert after==''
 record('S02',{'entered':'まだ保存していない計画の理由','afterOpeningAI':after});ctx.close()
 # Qualification subpage links must resolve against the shared application root.
 ctx,pg=fresh('ap/');pg.get_by_role('button',name='計画を登録',exact=True).click();open_plan_ai(pg);links=[]
 for name in ['公開フォーマット','JSON Schema']:
  href=pg.get_by_role('link',name=name,exact=True).evaluate('(el)=>el.href');response=pg.request.get(href);links.append({'label':name,'url':href,'status':response.status})
 assert all(x['status']==200 for x in links)
 record('C03',{'links':links,'status':'正常：資格別ページでもbaseにより共有ルートへ解決'});ctx.close()
 # Calendar day on home differs from the date used by the plan/AI summary.
 ctx,pg=fresh(zone='UTC',clock=datetime(2026,10,7,15,30,tzinfo=timezone.utc));pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();fixture=pg.evaluate('''async()=>{const s=await (async()=>{const {createLocalStore}=await import('/src/storage/local.js'),x=createLocalStore({qualificationId:'ap',rootPath:'/'});try{return JSON.parse(await x.snapshot());}finally{await x.close();}})();const a=s.attempts[0];a.startedAt='2026-10-07T14:30:00.000Z';a.updatedAt=a.startedAt;a.completedAt=a.startedAt;a.status='correct';a.selected=a.questionSnapshot.answer;a.selectedChoiceId=a.questionSnapshot.correctChoiceId;a.hintsBeforeAnswer=0;s.currentId=null;s.view='home';return s;}''');write_state(pg,fixture);pg.reload();pg.locator('.today-progress').wait_for();home=pg.locator('.today-progress').inner_text();calculation=pg.evaluate('''async()=>{const {summarize}=await import('/src/domain/planning.js'),q=await (await fetch('/content/ap/qualification.json')).json(),{createLocalStore}=await import('/src/storage/local.js'),s=createLocalStore({qualificationId:'ap',rootPath:'/'});try{const raw=JSON.parse(await s.snapshot());return summarize(raw.attempts,q,'Asia/Tokyo');}finally{await s.close();}}''');nav(pg,'history');historyToday=pg.locator('.motivation-panel .heading-row .badge').inner_text();assert '今日 0回' in home and '今日 1問' in historyToday and calculation['todayCounts']['completedAttempts']==0
 record('S04',{'deviceZone':'UTC','now':'2026-10-07T15:30:00Z','answerAt':'2026-10-07T14:30:00Z','home':home,'historyToday':historyToday,'summaryDate':calculation['today'],'summaryToday':calculation['todayCounts']['completedAttempts']});ctx.close()
 # Ordinary record restore and workspace restore are two separate commits.
 ctx,pg=fresh();pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();before=state(pg);backup=json.loads(json.dumps(before));backup['attempts'][0]['id']='audit-import-attempt';backup['currentId']='audit-import-attempt';backup['session']['attemptIds']=['audit-import-attempt'];backup['workspaceBackup']={'format':'hitomon-workspace-backup','version':1,'qualificationId':'ap','plan':{'format':'hitomon-study-plan','version':1,'qualificationId':'ap','timeZone':'Asia/Tokyo','examDates':[{'examPartId':'objective','date':'2026-11-04'}],'phases':[]},'runs':[]}
 pg.evaluate('''()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='outbox')throw new DOMException('audit full','QuotaExceededError');return original.apply(this,args);};}''');pg.locator('#settings-button').click();pg.locator('#import-state').set_input_files({'name':'audit-backup.json','mimeType':'application/json','buffer':json.dumps(backup).encode()});pg.wait_for_function('document.getElementById("settings-status").textContent.includes("保存できていません")');regular=state(pg);workspace=pg.evaluate(READ_WORKSPACE);assert regular['attempts'][0]['id']==before['attempts'][0]['id'];assert workspace[0]['payload']['examDates'][0]['date']=='2026-11-04'
 record('S05',{'ordinaryRecordRestored':False,'planRestored':True,'status':pg.locator('#settings-status').inner_text(),'date':workspace[0]['payload']['examDates'][0]['date']});ctx.close()
 # Real planning feature + DOM, synthetic incoming document, no Firebase account.
 ctx=b.new_context();pg=ctx.new_page();pg.goto(BASE+'docs/requirements.html');data=pg.evaluate('''async()=>{const {loadCatalog}=await import('/src/content/catalog.js'),content=await loadCatalog('ap'),{createLocalStore}=await import('/src/storage/local.js'),store=createLocalStore({qualificationId:'ap',rootPath:'/audit-planning/'}),{makeState}=await import('/src/domain/study.js'),state=makeState();state.view='planning';const {createPlanningFeature}=await import('/src/features/planning.js');document.body.innerHTML='<main id="main"></main>';let feature;feature=createPlanningFeature({qualification:content.manifest,rootPath:'/audit-planning/',getStore:()=>store,getState:()=>state,getNavigation:()=>0,content,base:content.questions,validateAttempt:()=>{},onUpdate:options=>{if(!options?.preserveForm)document.getElementById('main').innerHTML=feature.views().planningHTML();},onNavigate:()=>{},onNotice:()=>{},onChanged:()=>{},getReviewCount:()=>0,download:()=>{}});await feature.bind();await feature.action({dataset:{action:'open-ai'}});const text='{"still":"unsaved JSON"}';document.getElementById('plan-json').value=text;feature.input(document.getElementById('plan-json'));const identity=await store.identity(),{blankPlan}=await import('/src/domain/planning.js');feature.onDocuments([{...identity,id:'planning',kind:'planning',localRevision:1,payload:{...blankPlan(content.manifest),examDates:[{examPartId:'objective',date:'2026-11-04'}]}}]);const stale=!document.getElementById('planning-stale').hidden;await feature.action(document.querySelector('[data-action=reload-planning]'));const after=document.getElementById('plan-json').value;await feature.store().close();await store.close();return {stale,entered:text,after};}''');assert data['stale'] and data['after']==data['entered'];record('S06',data);ctx.close()
 b.close()
OUT.joinpath('browser-findings.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
