import {chooseNextAction,chooseFieldAction} from '../src/domain/next-action.js';
import {selectPractice} from '../src/domain/practice.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {validateLearning,learningId,contextPayload,applyLearning,scopeBelongsToQualification} from '../src/domain/learning-state.js';
import {makeState} from '../src/domain/study.js';
const scope={intent:'review',topicId:'db',topicIds:[],examPartId:'a',examPartIds:[],paperMode:'desk',returnView:'review',returnRunId:null};
const a={id:'attempt',questionId:'question',entryMode:'desk',practiceScope:scope};
test('contexts carry review/field/part/mode without answer material or page state',()=>{const p=contextPayload(a);assert.equal(learningId('context',p),'context--attempt');assert.deepEqual(p.scope,scope);assert.equal(contextPayload({...a,diagnosticRunId:'diagnostic'}),null);});
test('malformed settings, scope, actions and arbitrary extra data are rejected',()=>{
 for(const p of [{questionId:'q',value:'true'},{questionId:'../q',value:true},{questionId:'q',value:true,answer:'secret'}])assert.throws(()=>validateLearning('desk',p));
 for(const patch of [{entryMode:'unknown'},{scope:{...scope,paperMode:'all'}},{scope:{...scope,topicIds:['db','db']}},{scope:{...scope,returnView:'javascript:alert(1)'}},{scope:{...scope,returnSession:{}}}])assert.throws(()=>validateLearning('context',{...contextPayload(a),...patch}));
 assert.throws(()=>validateLearning('planning',{}));
});
test('desk releases remain explicit records and preserve unrelated preferences',()=>{const s=makeState();s.settings.deskQuestionIds=['old','q'];applyLearning(s,[{kind:'desk',payload:{questionId:'q',value:false}}]);assert.deepEqual(s.settings.deskQuestionIds,['old']);applyLearning(s,[{kind:'desk',payload:{questionId:'new',value:true}}]);assert.deepEqual(s.settings.deskQuestionIds,['old','new']);});
test('deferred release clears all trials and the current exclusion list',()=>{const s=makeState();s.attempts=[{id:'parent',questionId:'q',deferred:true},{id:'child',questionId:'q',deferred:true},{id:'other',questionId:'other',deferred:true}];s.session.excludedQuestionIds=['q','other'];applyLearning(s,[{kind:'deferred',payload:{questionId:'q',value:false}}]);assert.deepEqual(s.session.excludedQuestionIds,['other']);assert.deepEqual(s.attempts.map(a=>a.deferred),[false,false,true]);});
test('scope metadata can arrive before its answer, and cannot move an open question',()=>{const s=makeState(),doc={kind:'context',payload:contextPayload(a)};assert.equal(applyLearning(s,[doc]),false);s.attempts=[{id:'attempt',questionId:'question'}];assert.equal(applyLearning(s,[doc]),true);assert.equal(s.attempts[0].practiceScope.intent,'review');s.view='study';s.currentId='attempt';s.attempts[0].entryMode='all';applyLearning(s,[doc]);assert.equal(s.attempts[0].entryMode,'all');});

test('unknown qualification scope is ignored without poisoning ordinary answers',()=>{const s=makeState(),qual={id:'ap',topics:[{id:'db'}],examParts:[{id:'a'}]},p=contextPayload(a);s.attempts=[{id:'attempt',questionId:'question',questionSnapshot:{topicId:'db',examPartId:'a'}}];assert.equal(scopeBelongsToQualification(p,qual),true);const bad={...p,scope:{...p.scope,examPartIds:['removed-part']}};assert.equal(applyLearning(s,[{kind:'context',payload:bad}],qual),false);assert.equal(s.attempts[0].practiceScope,undefined);assert.equal(applyLearning(s,[{kind:'context',payload:p}],qual),true);});

test('existing but different topic or part cannot be applied to the source question',()=>{const s=makeState(),qual={id:'ap',topics:[{id:'db'},{id:'network'}],examParts:[{id:'a'},{id:'b'}]},p=contextPayload(a);s.attempts=[{id:'attempt',questionId:'question',questionSnapshot:{topicId:'db',examPartId:'a'}}];for(const scope of [{...p.scope,topicId:'network'},{...p.scope,examPartId:'b'},{...p.scope,topicIds:['network']},{...p.scope,examPartIds:['b']},{...p.scope,topicId:'network',topicIds:['db']},{...p.scope,examPartId:'b',examPartIds:['a']}])assert.equal(applyLearning(s,[{kind:'context',payload:{...p,scope}}],qual),false);assert.equal(s.attempts[0].practiceScope,undefined);});

test('canonical deferral excludes home, field and continuous selection despite an older deferred trial',()=>{const qualification={id:'ap',topics:[{id:'db'}],examParts:[{id:'a',practiceAvailable:true}]},questions=[{id:'q',topicId:'db',examPartId:'a'}],attempts=[{id:'old',questionId:'q',status:'postponed',deferred:true,updatedAt:'2025-01-01',startedAt:'2025-01-01'},{id:'later',questionId:'q',status:'independent',completedAt:'2026-01-01',startedAt:'2026-01-01'}],options={qualification,questions,attempts,reviewInfo:()=>null,excludedQuestionIds:['q']};for(const select of [selectPractice,chooseNextAction,o=>chooseFieldAction({...o,topicId:'db',paperMode:'all'})])assert.equal(select(options).kind,'unavailable');});
