"""Train-study filter, flashcards and atomic separate records in the real browser."""
import os,json,shutil
from pathlib import Path
DECK_COUNT=len(json.loads((Path(__file__).resolve().parents[1]/'content/ap/flashcards.json').read_text())['cards'])
from playwright.sync_api import sync_playwright
from browser_storage import state,nav
URL=os.getenv('AP_STUDY_URL','http://127.0.0.1:4173/')
ART=Path(os.getenv('AP_STUDY_ARTIFACTS','/workspace/scratch/mobile-study'));ART.mkdir(exist_ok=True)
READ_CARDS='''async()=>{const root=new URL('.',document.baseURI);const {createCardStore}=await import(new URL('src/storage/cards.js',root));const {createLocalStore}=await import(new URL('src/storage/local.js',root));const main=createLocalStore({rootPath:root.pathname,qualificationId:'ap'});const {owner}=await main.identity();await main.close();const cards=createCardStore({rootPath:root.pathname,owner,qualificationId:'ap'});try{return await cards.read();}finally{await cards.close();}}'''
with sync_playwright() as p:
 opts={'executable_path':shutil.which('chromium'),'args':['--no-sandbox']}
 if URL.startswith('https://') and os.getenv('HTTPS_PROXY'):opts['proxy']={'server':os.environ['HTTPS_PROXY'],'bypass':'127.0.0.1,localhost'}
 b=p.chromium.launch(**opts);ctx=b.new_context(viewport={'width':390,'height':844});pg=ctx.new_page();pg.set_default_timeout(15000);errors=[];requests=[];pg.on('pageerror',lambda e:errors.append(str(e)));pg.on('request',lambda r:requests.append(r.url));pg.goto(URL);pg.locator('.hero-start .primary').wait_for();assert not any('/data/qualifications/ap/flashcards.' in r for r in requests)
 assert pg.locator('.hero-start .primary').bounding_box()['y']<844
 # Start a real written-calculation problem, preserve partial work when switching contexts.
 nav(pg,'materials');pg.locator('[name=year]').select_option('2025');pg.locator('[name=season]').select_option('春期');pg.locator('[name=query]').fill('');pg.locator('[data-action=start][data-id="r07h-q18"]').click();pg.get_by_role('button',name='ヒントを1つ見る',exact=True).click();pg.get_by_role('radio').first.check();pg.get_by_role('button',name='中断',exact=True).click();paused=state(pg)['attempts'][-1]
 entry=lambda mode:pg.locator(f'.study-entrance[data-paper-mode="{mode}"]')
 candidate=entry('paperless').get_attribute('data-id');assert candidate!='r07h-q18';entry('paperless').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();s=state(pg);assert s['session']['paperMode']=='paperless';assert s['attempts'][-1]['questionId']==candidate
 pg.get_by_role('button',name='ヒントを1つ見る',exact=True).click();pg.get_by_role('radio').first.check();assert pg.locator('[data-action=desk-later]').is_visible();assert pg.locator('.study-options summary').count()==0;assert pg.locator('[data-action=desk-later]').evaluate('(el)=>getComputedStyle(el).color')=='rgb(157, 55, 69)';pg.locator('[data-action=desk-later]').scroll_into_view_if_needed();pg.screenshot(path=str(ART/'paper-required.png'),full_page=False);assert pg.locator('.question-panel [data-action=desk-later]').count()==0;assert pg.locator('.answer-actions [data-action=desk-later]').count()==0;pg.get_by_role('button',name='この問題は紙ペンが必要',exact=True).click();s=state(pg);assert candidate in s['settings']['deskQuestionIds'];marked=s['attempts'][-1];assert marked['hintCount']==1 and marked['selected']==0 and marked['status']=='postponed';assert entry('paperless').get_attribute('data-id')!=candidate
 assert next(a for a in s['attempts'] if a['id']==paused['id'])['hintCount']==1
 entry('desk').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();assert state(pg)['currentId']==marked['id'];pg.get_by_role('button',name='中断',exact=True).click()
 # A filter changed in another tab cannot broaden an ongoing paperless session.
 entry('paperless').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();other=ctx.new_page();other.goto(URL);other.get_by_role('button',name='回答する',exact=True).wait_for();nav(other,'topics');other.locator('[data-action=paper-mode][data-mode=all]').click();other.locator('[data-mode=all][aria-pressed=true]').wait_for();state(other);other.close();pg.reload();pg.get_by_role('button',name='回答する',exact=True).wait_for();s=state(pg);a=next(a for a in s['attempts'] if a['id']==s['currentId']);assert s['settings']['paperMode']=='all' and s['session']['paperMode']=='paperless';pg.get_by_role('radio').nth(a['questionSnapshot']['answer']).check();pg.get_by_role('button',name='回答する',exact=True).click();pg.get_by_role('button',name='もう1問',exact=True).click();pg.get_by_role('button',name='回答する',exact=True).wait_for();s=state(pg);assert s['session']['paperMode']=='paperless';a=next(a for a in s['attempts'] if a['id']==s['currentId']);assert a['questionId'] in {i['questionId'] for i in json.loads((Path(__file__).resolve().parents[1]/'content/ap/study-context.json').read_text())['items'] if i['mode']=='paperless'};pg.get_by_role('button',name='中断',exact=True).click()
 # Flashcard back and rating are hidden until reveal; records persist separately.
 before=state(pg);pg.get_by_role('button',name=f'単語帳 · {DECK_COUNT}枚',exact=True).click();pg.get_by_role('button',name='意味を見る',exact=True).wait_for();assert not pg.locator('.card-back').count();front=pg.locator('.flashcard h2').inner_text();pg.get_by_role('button',name='意味を見る',exact=True).click();pg.locator('.card-back').wait_for();pg.reload();pg.locator('.card-back').wait_for();assert pg.locator('.flashcard h2').inner_text()==front
 pg.get_by_role('button',name='思い出せた → 次へ',exact=True).click();pg.get_by_role('button',name='意味を見る',exact=True).wait_for();assert pg.locator('.flashcard h2').inner_text()!=front;cards=pg.evaluate(READ_CARDS);assert len(cards['events'])==1 and cards['events'][0]['outcome']=='recalled';after=state(pg);assert after['attempts']==before['attempts'];assert after['session']==before['session']
 pg.locator('[name=card-topic]').select_option('security');pg.get_by_role('button',name='意味を見る',exact=True).wait_for();pg.wait_for_function('document.querySelector(".flashcard").textContent.includes("セキュリティ")');pg.get_by_role('button',name='意味を見る',exact=True).click();pg.locator('.flashcard details > summary').click();assert pg.get_by_role('button',name='過去問で確認する',exact=True).is_visible()
 # Real IDB import is idempotent and atomic even if conflicts follow new rows; namespaces are isolated.
 result=pg.evaluate('''async()=>{const root=new URL('.',document.baseURI),{createCardStore}=await import(new URL('src/storage/cards.js',root));const s=createCardStore({rootPath:root.pathname,owner:'test-cards',qualificationId:'ap'}),other=createCardStore({rootPath:root.pathname,owner:'other-cards',qualificationId:'ap'}),q=createCardStore({rootPath:root.pathname,owner:'test-cards',qualificationId:'other'});const e={id:'event-1',cardId:'one',cardVersion:1,outcome:'again',at:'2026-10-07T01:00:00.000Z'};await s.importEvents([e]);await s.importEvents([{at:e.at,outcome:e.outcome,cardVersion:1,cardId:'one',id:e.id}]);let rejected=false;try{await s.importEvents([{...e,id:'event-2'},{...e,outcome:'recalled'}]);}catch{rejected=true;}const results=[rejected,(await s.read()).events.length,(await other.read()).events.length,(await q.read()).events.length];await Promise.all([s.close(),other.close(),q.close()]);return results;}''');assert result==[True,1,0,0],result
 pg.locator('.card-data > summary').click();beforecards=pg.evaluate(READ_CARDS);pg.locator('#import-cards').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':json.dumps({'format':'hitomon-card-record','version':1,'qualificationId':'other','events':[]}).encode()});assert pg.evaluate(READ_CARDS)==beforecards
 for width in [320,390]:
  pg.set_viewport_size({'width':width,'height':844});pg.evaluate('document.documentElement.style.fontSize="32px"');assert pg.evaluate('document.documentElement.scrollWidth<=innerWidth');pg.screenshot(path=str(ART/f'cards-{width}-200.png'),full_page=True);pg.evaluate('document.documentElement.style.fontSize=""')
 # Separate backup round-trip and deletion do not touch normal question records.
 pg.on('dialog',lambda d:d.accept())
 with pg.expect_download() as d:pg.get_by_role('button',name='単語帳の記録を書き出す',exact=True).click()
 backup=ART/'card-record.json';d.value.save_as(str(backup));pg.get_by_role('button',name='単語帳の記録を削除',exact=True).click();pg.wait_for_function('document.querySelector("#main").textContent.includes("確認済み 0")');assert state(pg)['attempts']==before['attempts']
 pg.locator('.card-data > summary').click();pg.locator('#import-cards').set_input_files(str(backup));pg.wait_for_function('document.querySelector("#main").textContent.includes("確認済み 1")');assert len(pg.evaluate(READ_CARDS)['events'])==1
 pg.set_viewport_size({'width':390,'height':844});pg.screenshot(path=str(ART/'cards.png'),full_page=True);pg.get_by_role('button',name='ホーム',exact=True).click();pg.screenshot(path=str(ART/'home.png'),full_page=True)
 # Explicit IDs open both table-reading and calculation questions, irrespective of the previous entrance.
 nav(pg,'topics');pg.locator('[data-action=paper-mode][data-mode=paperless]').click();pg.locator('[data-mode=paperless][aria-pressed=true]').wait_for();nav(pg,'materials');pg.locator('[name=year]').select_option('2025');pg.locator('[name=season]').select_option('spring');pg.locator('[name=query]').fill('2025年 春期 問16');pg.locator('[data-action=start][data-id="r07h-q16"]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();s=state(pg);assert s['session']['paperMode']=='all' and s['session']['intent']=='direct' and next(a for a in s['attempts'] if a['id']==s['currentId'])['questionId']=='r07h-q16';pg.get_by_role('button',name='中断',exact=True).click()
 nav(pg,'materials');pg.locator('[name=query]').fill('2025年 春期 問8');count=len(state(pg)['attempts']);pg.locator('[data-action=start][data-id="r07h-q8"]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();assert len(state(pg)['attempts'])==count+1;assert state(pg)['session']['paperMode']=='all';assert pg.get_by_role('button',name='元の画面に戻る',exact=True).is_visible()
 # Opened deck and checkpoint remain usable offline through the service worker.
 nav(pg,'home');pg.get_by_role('button',name=f'単語帳 · {DECK_COUNT}枚',exact=True).click();pg.locator('.flashcard').wait_for();pg.evaluate('navigator.serviceWorker.ready');ctx.set_offline(True);pg.reload();pg.locator('.flashcard').wait_for();assert '中断位置はこの端末に保存します' in pg.locator('#main').inner_text();ctx.set_offline(False)
 assert not errors,errors;b.close()
print('PASS paperless exact candidate / desk override / partial work retained / flip then rate / separate attempts / resume / atomic IDB imports / namespace isolation / 320px 200% / offline deck')
