from browser_storage import nav as action_nav, open_plan_editor, open_plan_ai
"""Week targets and manual milestones: real UI, backup and offline preservation."""
import json,shutil,tempfile
from datetime import datetime,timedelta
from zoneinfo import ZoneInfo
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_storage import state,wait_for_async
ROOT=Path(__file__).resolve().parents[1];ARTIFACTS=Path(tempfile.mkdtemp(prefix='hitomon-plan-targets-'))
READ='''async()=>{const {createLocalStore}=await import('/src/storage/local.js'),local=createLocalStore({qualificationId:'ap',rootPath:'/'});try{const identity=await local.identity(),{createWorkspaceStore}=await import('/src/storage/workspace.js'),workspace=createWorkspaceStore({...identity,rootPath:'/',validate:(kind,payload)=>payload});try{return (await workspace.read()).find(r=>r.id==='planning');}finally{await workspace.close();}}finally{await local.close();}}'''
today=datetime.now(ZoneInfo('Asia/Tokyo')).date();date=lambda n:(today+timedelta(days=n)).isoformat()
def open_targets(page):
 open_plan_editor(page)
 details=page.locator('#plan-editor .phase-targets').first
 if not details.evaluate('(d)=>d.open'):details.locator(':scope > summary').click()
 return details
def details_open(page,form):
 form.evaluate('(form)=>{for(let d=form.parentElement;d;d=d.parentElement)if(d.tagName==="DETAILS")d.open=true;}')
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=shutil.which('chromium'),args=['--no-sandbox']);context=browser.new_context(viewport={'width':390,'height':844},permissions=['clipboard-read','clipboard-write']);page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('dialog',lambda d:d.accept());page.goto('http://127.0.0.1:4173/')
 page.get_by_role('button',name='とりあえずはじめる',exact=True).click();page.get_by_role('button',name='回答する',exact=True).wait_for();record=state(page);answer=next(a for a in record['attempts'] if a['id']==record['currentId'])['questionSnapshot']['answer'];page.get_by_role('radio').nth(answer).check();page.get_by_role('button',name='回答する',exact=True).click();page.get_by_role('button',name='ホーム',exact=True).click();page.get_by_role('button',name='受験日・計画を登録',exact=True).click()
 open_plan_editor(page);open_plan_ai(page)
 form=page.locator('#phase-form');details_open(page,form);form.locator('[name=name]').fill('基礎確認');form.locator('[name=start]').fill(date(0));form.locator('[name=end]').fill(date(11));form.locator('[name=target]').fill('20');form.get_by_role('button',name='フェーズを追加',exact=True).click();page.get_by_text('フェーズを保存しました。',exact=True).wait_for()
 open_targets(page);week=page.locator('[data-planning-form=week]').first;details_open(page,week);week.locator('[name=start]').fill(date(0));week.locator('[name=end]').fill(date(6));week.locator('[name=target]').fill('10');week.get_by_role('button',name='週別目標を保存',exact=True).click();page.get_by_text('週別目標を保存しました。',exact=True).wait_for();open_targets(page);assert '10回予定 / 現在1回 / あと9回' in page.locator('#plan-editor .plan-target-row').inner_text()
 before=page.evaluate(READ);week=page.locator('[data-planning-form=week]').first;details_open(page,week);week.locator('[name=start]').fill(date(1));week.locator('[name=end]').fill(date(6));week.locator('[name=target]').fill('5');week.get_by_role('button',name='週別目標を保存',exact=True).click();page.get_by_text('週別目標の期間を重複させないでください',exact=False).wait_for();assert page.evaluate(READ)==before
 page.get_by_role('button',name='週別目標を編集',exact=True).click();week=page.locator('[data-planning-form=week]').first;assert week.locator('[name=target]').input_value()=='10';week.locator('[name=target]').fill('8');week.get_by_role('button',name='週別目標を保存',exact=True).click();page.get_by_text('週別目標を保存しました。',exact=True).wait_for();open_targets(page)
 week=page.locator('[data-planning-form=week]').first;details_open(page,week);week.locator('[name=start]').fill(date(7));week.locator('[name=end]').fill(date(11));week.locator('[name=target]').fill('12');week.get_by_role('button',name='週別目標を保存',exact=True).click();page.get_by_text('週別目標を保存しました。',exact=True).wait_for();open_targets(page)
 milestone=page.locator('[data-planning-form=milestone]').first;details_open(page,milestone);milestone.locator('[name=name]').fill('手元の記述式教材で模試');milestone.locator('[name=date]').fill(date(11));milestone.locator('[name=part]').select_option('written');milestone.get_by_role('button',name='予定を保存',exact=True).click();page.get_by_text('予定を保存しました。',exact=True).wait_for();open_targets(page);page.get_by_role('button',name='完了にする',exact=True).click();page.get_by_text('予定の完了状態を保存しました。',exact=True).wait_for();assert page.evaluate(READ)['payload']['phases'][0]['milestones'][0]['completed'];assert len([a for a in state(page)['attempts'] if a['completedAt']])==1
 open_targets(page);page.get_by_role('button',name='予定を編集',exact=True).click();milestone=page.locator('[data-planning-form=milestone]').first;milestone.locator('[name=name]').fill('記述式の確認');milestone.get_by_role('button',name='予定を保存',exact=True).click();page.get_by_text('予定を保存しました。',exact=True).wait_for();assert page.evaluate(READ)['payload']['phases'][0]['milestones'][0]['completed'];open_targets(page);page.get_by_role('button',name='未完了に戻す',exact=True).click();page.get_by_text('予定の完了状態を保存しました。',exact=True).wait_for()
 page.locator('#plan-editor .plan-phase').get_by_role('button',name='編集',exact=True).click();form=page.locator('#phase-form');form.locator('[name=name]').fill('基礎確認・改訂');form.locator('[name=target]').fill('30');form.get_by_role('button',name='変更を保存',exact=True).click();page.get_by_text('フェーズを保存しました。',exact=True).wait_for();plan=page.evaluate(READ)['payload'];assert len(plan['phases'][0]['weeklyTargets'])==2 and len(plan['phases'][0]['milestones'])==1
 open_plan_ai(page);invalid=json.loads(json.dumps(plan));invalid['phases'][0]['weeklyTargets'][0]['end']=date(7);page.locator('#plan-json').fill(json.dumps(invalid));page.get_by_role('button',name='検証してプレビュー',exact=True).click();page.get_by_text('フェーズ内の1〜7日間を指定してください',exact=False).wait_for();assert page.evaluate(READ)['payload']==plan
 page.get_by_role('button',name='学習状況JSONをコピー',exact=True).click();page.get_by_text('コピーしました。',exact=True).wait_for();summary=json.loads(page.evaluate('navigator.clipboard.readText()'));assert summary['phaseProgress'][0]['weeklyProgress'][0]['actual']==1 and summary['currentPlan']==plan
 page.get_by_role('button',name='ホーム',exact=True).click();assert page.locator('.week-progress').inner_text()=='今週 1 / 8回 · あと7回';assert page.locator('[data-action=start-session]').count()==1;page.get_by_role('button',name='計画を見る',exact=True).click()
 page.evaluate('document.querySelectorAll("#main details").forEach(d=>d.open=true);document.documentElement.style.fontSize="32px"');assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path=str(ARTIFACTS/'targets-mobile-200.png'),full_page=True)
 page.locator('#settings-button').click()
 with page.expect_download() as event:page.get_by_role('button',name='学習記録を書き出す',exact=True).click()
 backup=ARTIFACTS/'record.json';event.value.save_as(str(backup));assert json.loads(backup.read_text())['workspaceBackup']['plan']==plan;page.get_by_role('button',name='設定を閉じる').click()
 page.evaluate('async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener("controllerchange",r,{once:true}));}')
 context.set_offline(True);page.reload();page.get_by_role('heading',name='受験日・学習計画',exact=True).wait_for();assert page.evaluate(READ)['payload']==plan;open_targets(page);assert '8回予定 / 現在1回 / あと7回' in page.locator('.phase-targets').inner_text();context.set_offline(False)
 fresh=browser.new_context();other=fresh.new_page();other.on('pageerror',lambda e:errors.append(str(e)));other.goto('http://127.0.0.1:4173/');other.get_by_role('button',name='とりあえずはじめる',exact=True).wait_for();other.locator('#settings-button').click();other.locator('#import-state').set_input_files(str(backup));other.get_by_text('学習記録を読み込みました。',exact=True).wait_for();other.get_by_role('button',name='設定を閉じる').click();assert other.evaluate(READ)['payload']==plan
 page.locator('.sidebar [data-view=home]').click();page.get_by_role('button',name='計画を見る',exact=True).click();open_targets(page);page.get_by_role('button',name='週別目標を削除',exact=True).last.click();page.get_by_text('目標・予定を削除しました。',exact=True).wait_for();open_targets(page);page.get_by_role('button',name='予定を削除',exact=True).click();page.get_by_text('目標・予定を削除しました。',exact=True).wait_for();assert len(page.evaluate(READ)['payload']['phases'][0]['weeklyTargets'])==1 and not page.evaluate(READ)['payload']['phases'][0]['milestones'];assert other.evaluate(READ)['payload']==plan
 assert not errors,errors;browser.close()
print('PASS week add/edit/delete / invalid overlap unchanged / milestone part/date and manual completion / phase editing preserves targets / AI summary / home priority / backup restore / offline reload / mobile 200% / browser isolation')
print('Artifacts:',ARTIFACTS)
