"""Regression cases for planning drafts, failure recovery and calendar consistency.
Uses isolated guests and synthetic incoming documents, never a production account.
"""
import json,shutil,sys
from pathlib import Path
from datetime import datetime,timezone
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tests'))
from browser_storage import state,nav,write_state,open_plan_editor,open_plan_ai
BASE='http://127.0.0.1:4173/'
OUT=Path('/tmp/hitomon-spec-fix');OUT.mkdir(parents=True,exist_ok=True);results=[];errors=[]
def record(id,data):results.append({'id':id,**data});print(id,json.dumps(data,ensure_ascii=False),flush=True)
READ_WORKSPACE='''async()=>{const {createLocalStore}=await import('/src/storage/local.js'),s=createLocalStore({qualificationId:'ap',rootPath:'/'});const identity=await s.identity();await s.close();const {createWorkspaceStore}=await import('/src/storage/workspace.js'),w=createWorkspaceStore({...identity,rootPath:'/',validate:(k,p)=>p});try{return await w.read();}finally{await w.close();}}'''
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=shutil.which('chromium'),args=['--no-sandbox'])
 def fresh(path='',zone='Asia/Tokyo',clock=None,block_worker=False):
  ctx=b.new_context(viewport={'width':390,'height':844},timezone_id=zone,service_workers='block' if block_worker else 'allow');pg=ctx.new_page();pg.set_default_timeout(10000);pg.on('pageerror',lambda e:errors.append(str(e)));pg.on('dialog',lambda d:d.accept())
  if clock:pg.clock.install(time=clock)
  pg.goto(BASE+path);pg.locator('.study-entrance[data-paper-mode=all]').wait_for();pg.wait_for_function('document.getElementById("sync-state").textContent.includes("ログインすると、学習記録を同期できます。")');return ctx,pg
 # Failure injection: the storage transaction rejects; only this isolated guest is affected.
 ctx,pg=fresh();pg.locator('.study-entrance[data-paper-mode=paperless]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();pg.get_by_role('button',name='ヒントを1つ見る',exact=True).click();pg.get_by_role('radio').first.check();before=state(pg);aid=before['currentId']
 pg.evaluate('''()=>{const original=IDBObjectStore.prototype.put;window.__put=original;IDBObjectStore.prototype.put=function(...args){if(this.name==='outbox')throw new DOMException('audit full','QuotaExceededError');return original.apply(this,args);};}''')
 pg.get_by_role('button',name='この問題は紙ペンが必要',exact=True).click();pg.wait_for_function('document.getElementById("save-state").textContent==="保存できていません"');persisted=state(pg)
 assert persisted['currentId']==aid and not persisted['settings']['deskQuestionIds'];assert pg.get_by_role('button',name='回答する',exact=True).is_visible();assert pg.get_by_role('radio').first.is_checked();assert pg.locator('.hint-box').count()==1;pg.evaluate('()=>{IDBObjectStore.prototype.put=window.__put;}');pg.get_by_role('button',name='この問題は紙ペンが必要',exact=True).click();pg.locator('.study-entrance[data-paper-mode=desk]').wait_for();assert pg.locator('.study-entrance[data-paper-mode=desk]').get_attribute('data-id')==aid
 record('S01',{'screenAfterFailure':'study','persistedView':persisted['view'],'persistedCurrent':persisted['currentId'],'persistedDeskIds':persisted['settings']['deskQuestionIds'],'retrySucceeded':True});pg.screenshot(path=str(OUT/'desk-save-failure.png'));ctx.close()
 # Opening an adjacent planning block rerenders the unsaved manual form.
 ctx,pg=fresh();pg.get_by_role('button',name='計画を登録',exact=True).click();open_plan_editor(pg);f=pg.locator('#context-form');f.evaluate('(el)=>el.parentElement.open=true');f.locator('[name=rationale]').fill('まだ保存していない計画の理由');pg.get_by_role('button',name='AIに相談・JSONを登録',exact=True).click();after=pg.locator('#context-form [name=rationale]').input_value();assert after=='まだ保存していない計画の理由'
 record('S02',{'entered':'まだ保存していない計画の理由','afterOpeningAI':after})
 open_plan_editor(pg);exam=pg.locator('#exam-form');exam.locator('[name=exam-objective]').fill('2026-11-04');phase=pg.locator('#phase-form');phase.evaluate('(el)=>el.parentElement.open=true');phase.locator('[name=name]').fill('未保存のフェーズ');phase.locator('[name=end]').fill('2026-11-10');phase.locator('[name=target]').fill('20');phase.locator('input[name=topic][value=security]').evaluate('(el)=>{for(let d=el.parentElement;d;d=d.parentElement)if(d.tagName==="DETAILS")d.open=true;}');phase.locator('input[name=topic][value=security]').check();pg.get_by_role('button',name='AIに相談・JSONを登録',exact=True).click();assert pg.locator('#exam-form [name=exam-objective]').input_value()=='2026-11-04' and pg.locator('#phase-form [name=name]').input_value()=='未保存のフェーズ' and pg.locator('#phase-form input[value=security]').is_checked()
 pg.locator('#plan-json').fill('{invalid');pg.get_by_role('button',name='検証してプレビュー',exact=True).click();assert pg.locator('#context-form [name=rationale]').input_value()=='まだ保存していない計画の理由';pg.locator('#exam-form').get_by_role('button',name='受験日を保存',exact=True).click();pg.get_by_text('受験日を保存しました。',exact=True).wait_for();assert pg.locator('#phase-form [name=name]').input_value()=='未保存のフェーズ';pg.locator('#context-form').get_by_role('button',name='前提を保存',exact=True).click();pg.get_by_text('計画の前提を保存しました。',exact=True).wait_for();assert pg.locator('#phase-form [name=name]').input_value()=='未保存のフェーズ';nav(pg,'home');pg.get_by_role('button',name='計画を見る',exact=True).click();assert pg.locator('#phase-form [name=name]').input_value()=='未保存のフェーズ' and pg.locator('#phase-form input[value=security]').is_checked();record('S02B',{'otherFormsPreserved':True,'ownRevisionAdvanced':True,'navigationPreserved':True,'invalidPreviewPreserved':True});ctx.close()
 # Qualification subpage links must resolve against the shared application root.
 ctx,pg=fresh('ap/');pg.get_by_role('button',name='計画を登録',exact=True).click();open_plan_ai(pg);links=[]
 for name in ['公開フォーマット','JSON Schema']:
  href=pg.get_by_role('link',name=name,exact=True).evaluate('(el)=>el.href');response=pg.request.get(href);links.append({'label':name,'url':href,'status':response.status})
 assert all(x['status']==200 for x in links)
 record('C03',{'links':links,'status':'正常：資格別ページでもbaseにより共有ルートへ解決'});ctx.close()
 # Home/history/AI share the plan calendar day.
 ctx,pg=fresh(zone='UTC',clock=datetime(2026,10,7,15,30,tzinfo=timezone.utc));pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();fixture=pg.evaluate('''async()=>{const s=await (async()=>{const {createLocalStore}=await import('/src/storage/local.js'),x=createLocalStore({qualificationId:'ap',rootPath:'/'});try{return JSON.parse(await x.snapshot());}finally{await x.close();}})();const a=s.attempts[0];a.startedAt='2026-10-07T14:30:00.000Z';a.updatedAt=a.startedAt;a.completedAt=a.startedAt;a.status='correct';a.selected=a.questionSnapshot.answer;a.selectedChoiceId=a.questionSnapshot.correctChoiceId;a.hintsBeforeAnswer=0;s.currentId=null;s.view='home';return s;}''');write_state(pg,fixture);pg.reload();pg.locator('.today-progress').wait_for();home=pg.locator('.today-progress').inner_text();calculation=pg.evaluate('''async()=>{const {summarize}=await import('/src/domain/planning.js'),q=await (await fetch('/content/ap/qualification.json')).json(),{createLocalStore}=await import('/src/storage/local.js'),s=createLocalStore({qualificationId:'ap',rootPath:'/'});try{const raw=JSON.parse(await s.snapshot());return summarize(raw.attempts,q,'Asia/Tokyo');}finally{await s.close();}}''');nav(pg,'history');historyToday=pg.locator('.motivation-panel .heading-row .badge').inner_text();assert '今日 0回' in home and '今日 0問' in historyToday and calculation['todayCounts']['completedAttempts']==0
 record('S04',{'deviceZone':'UTC','now':'2026-10-07T15:30:00Z','answerAt':'2026-10-07T14:30:00Z','home':home,'historyToday':historyToday,'summaryDate':calculation['today'],'summaryToday':calculation['todayCounts']['completedAttempts']});ctx.close()
 # Two JST study days remain two days on UTC/JST/New York devices.
 for zone in ['UTC','Asia/Tokyo','America/New_York']:
  ctx,pg=fresh(zone=zone,clock=datetime(2026,10,7,15,30,tzinfo=timezone.utc));both=json.loads(json.dumps(fixture));second=json.loads(json.dumps(both['attempts'][0]));second['id']='today-attempt';second['startedAt']=second['updatedAt']=second['completedAt']='2026-10-07T15:15:00.000Z';both['attempts'].append(second);write_state(pg,both);pg.reload();pg.locator('.today-progress').wait_for();assert '今日 1回' in pg.locator('.today-progress').inner_text();nav(pg,'history');assert '今日 1問' in pg.locator('.motivation-panel .badge').inner_text();assert '直近7日 2日' in pg.locator('.progress-counts').inner_text();pg.locator('.achievements > summary').click();assert pg.locator('.calendar-day.studied').count()==2;assert pg.locator('.calendar-day.today').get_attribute('aria-label')=='10月8日、1問に取り組みました';assert pg.get_by_text('2日以上学習',exact=True).is_visible();ctx.close()
 record('S04B',{'deviceZones':['UTC','Asia/Tokyo','America/New_York'],'today':1,'studyDays':2,'calendarToday':'10月8日'})
 # Ordinary record restore and workspace restore are two separate commits.
 ctx,pg=fresh();pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();before=state(pg);backup=json.loads(json.dumps(before));backup['attempts'][0]['id']='audit-import-attempt';backup['currentId']='audit-import-attempt';backup['session']['attemptIds']=['audit-import-attempt'];backup['workspaceBackup']={'format':'hitomon-workspace-backup','version':1,'qualificationId':'ap','plan':{'format':'hitomon-study-plan','version':1,'qualificationId':'ap','timeZone':'Asia/Tokyo','examDates':[{'examPartId':'objective','date':'2026-11-04'}],'phases':[]},'runs':[]}
 pg.evaluate('''()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='outbox')throw new DOMException('audit full','QuotaExceededError');return original.apply(this,args);};}''');pg.locator('#settings-button').click();pg.locator('#import-state').set_input_files({'name':'audit-backup.json','mimeType':'application/json','buffer':json.dumps(backup).encode()});pg.wait_for_function('document.getElementById("settings-status").textContent.includes("取り込めませんでした")');regular=state(pg);workspace=pg.evaluate(READ_WORKSPACE);assert regular['attempts'][0]['id']==before['attempts'][0]['id'];assert not workspace;assert '現在の記録と計画は変更していません' in pg.locator('#settings-status').inner_text()
 record('S05',{'ordinaryRecordRestored':False,'planRestored':False,'status':pg.locator('#settings-status').inner_text(),'workspaceCount':len(workspace)});ctx.close()
 # A late workspace failure is a clearly reported partial restore; the batch is atomic.
 ctx,pg=fresh();pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_role('button',name='回答する',exact=True).wait_for();before=state(pg);backup=json.loads(json.dumps(before));backup['attempts'][0]['id']='restored-attempt';backup['currentId']='restored-attempt';backup['session']['attemptIds']=['restored-attempt']
 runs=pg.evaluate("""async()=>{const {loadCatalog}=await import('/src/content/catalog.js'),c=await loadCatalog('ap'),{createDiagnostic,finishDiagnostic}=await import('/src/domain/diagnostic.js');const questions=c.questions.slice(0,30);await Promise.all(questions.map(q=>c.ensure(q.id)));return [0,1].map(()=>{const r=createDiagnostic(questions,c.manifest);finishDiagnostic(r);return r;});}""")
 backup['workspaceBackup']={'format':'hitomon-workspace-backup','version':1,'qualificationId':'ap','plan':{'format':'hitomon-study-plan','version':1,'qualificationId':'ap','timeZone':'Asia/Tokyo','examDates':[{'examPartId':'objective','date':'2026-11-04'}],'phases':[]},'runs':runs}
 pg.evaluate("""()=>{window.__add=IDBObjectStore.prototype.add;let calls=0;IDBObjectStore.prototype.add=function(...args){if(this.name==='documents'&&++calls===2)throw new DOMException('workspace full','QuotaExceededError');return window.__add.apply(this,args);};}""");pg.locator('#settings-button').click();file={'name':'complete-backup.json','mimeType':'application/json','buffer':json.dumps(backup).encode()};pg.locator('#import-state').set_input_files(file);pg.wait_for_function('document.getElementById("settings-status").textContent.includes("通常演習の記録は読み込み済み" )');assert state(pg)['currentId']=='restored-attempt';assert pg.evaluate(READ_WORKSPACE)==[];pg.evaluate('()=>{IDBObjectStore.prototype.add=window.__add;}');pg.reload();pg.get_by_role('button',name='回答する',exact=True).wait_for();assert state(pg)['currentId']=='restored-attempt' and pg.evaluate(READ_WORKSPACE)==[];pg.locator('#settings-button').click()
 pg.locator('#import-state').set_input_files(file);pg.wait_for_function('document.getElementById("settings-status").textContent.includes("診断2件を追加")');docs=pg.evaluate(READ_WORKSPACE);assert len(docs)==3;pg.locator('#import-state').set_input_files(file);pg.wait_for_function('document.getElementById("settings-status").textContent.includes("診断0件を追加、2件は登録済み")');assert len(pg.evaluate(READ_WORKSPACE))==3;assert '既存の受験日・計画は保持しました' in pg.locator('#settings-status').inner_text();record('S05B',{'partialClearlyReported':True,'workspaceBatchRolledBack':True,'reloadMatchesCommittedState':True,'retryRuns':2,'duplicateRuns':0});ctx.close()
 # An earlier slow question load must not replace a subsequently imported record.
 ctx,pg=fresh(block_worker=True);empty=pg.evaluate("async()=>{const {makeState}=await import('/src/domain/study.js');return makeState();}");pending=[];pg.route('**/data/qualifications/ap/packs/**',lambda route:pending.append(route));pg.locator('.study-entrance[data-paper-mode=all]').click();pg.get_by_text('教材を読み込んでいます。',exact=True).wait_for();pg.wait_for_function('document.getElementById("main").getAttribute("aria-busy")==="true"');pg.locator('#settings-button').click();pg.locator('#import-state').set_input_files({'name':'empty.json','mimeType':'application/json','buffer':json.dumps(empty).encode()});pg.get_by_text('学習記録を読み込みました。',exact=True).wait_for();assert pending
 with pg.expect_response('**/data/qualifications/ap/packs/**') as response:pending.pop(0).continue_()
 response.value.body();pg.evaluate('()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');assert not state(pg)['attempts'] and state(pg)['view']=='home';record('S05C',{'oldQuestionLoadCancelled':True,'importedEmptyRecordPreserved':True});ctx.close()
 # Real planning feature + DOM, synthetic incoming document, no Firebase account.
 ctx=b.new_context();pg=ctx.new_page();pg.on('pageerror',lambda e:errors.append(str(e)));pg.goto(BASE+'docs/spec-behavior-review.html');data=pg.evaluate('''async()=>{const {loadCatalog}=await import('/src/content/catalog.js'),content=await loadCatalog('ap'),{createLocalStore}=await import('/src/storage/local.js'),store=createLocalStore({qualificationId:'ap',rootPath:'/audit-planning/'}),{makeState}=await import('/src/domain/study.js'),state=makeState();state.view='planning';const {createPlanningFeature}=await import('/src/features/planning.js');document.body.innerHTML='<main id="main"></main>';let feature;feature=createPlanningFeature({qualification:content.manifest,rootPath:'/audit-planning/',getStore:()=>store,getState:()=>state,getNavigation:()=>0,content,base:content.questions,validateAttempt:()=>{},onUpdate:options=>{if(!options?.preserveForm){document.getElementById('main').innerHTML=feature.views().planningHTML();feature.restoreDrafts();}},onNavigate:()=>{},onNotice:()=>{},onChanged:()=>{},getReviewCount:()=>0,download:()=>{}});await feature.bind();await feature.action({dataset:{action:'open-ai'}});const text='{"still":"unsaved JSON"}';document.getElementById('plan-json').value=text;feature.input(document.getElementById('plan-json'));const identity=await store.identity(),{blankPlan}=await import('/src/domain/planning.js');feature.onDocuments([{...identity,id:'planning',kind:'planning',localRevision:1,payload:{...blankPlan(content.manifest),examDates:[{examPartId:'objective',date:'2026-11-04'}]}}]);const stale=!document.getElementById('planning-stale').hidden;await feature.action(document.querySelector('[data-action=reload-planning]'));const after=document.getElementById('plan-json').value;await feature.store().close();await store.close();return {stale,entered:text,after};}''');assert data['stale'] and data['after']=='';record('S06',data);ctx.close()
 assert not errors,errors
 b.close()
OUT.joinpath('browser-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2))
