import {upcomingExam} from '../domain/analytics.js';
import {esc,dateText} from '../utils.js';
import {blankPlan,examPartsFor,dateInZone,daysBetween,phaseProgress} from '../domain/planning.js';
import {planTargetsHTML} from './plan-targets.js';
import {contextHTML,contextFormHTML,summaryPreviewHTML} from './plan-context.js';
import {diagnosticResult,diagnosticAttempts,diagnosticSlots} from '../domain/diagnostic.js';

export function createPlanningViews({qualification,documents,attempts,currentRunId,preview,jsonInput='',editingPhaseId=null,editingWeek=null,editingMilestone=null,workspaceStatus='guest',summaryData,editorOpen=false,aiOpen=false,targetPartId=null}){
 const planRow=documents.find(r=>r.id==='planning'),plan=planRow?.payload||blankPlan(qualification),parts=examPartsFor(qualification);
 const runs=documents.filter(r=>r.kind==='diagnostic').sort((a,b)=>b.payload.startedAt.localeCompare(a.payload.startedAt));
 const active=runs.find(r=>r.payload.status==='in_progress'),finished=runs.filter(r=>r.payload.status!=='in_progress');
 const runRow=runs.find(r=>r.id===currentRunId),run=runRow?.payload;
 const progress=phaseProgress(plan,attempts,qualification),phase=progress.find(p=>p.active),week=phase?.weeklyProgress.find(w=>w.active);
 const partName=id=>parts.find(p=>p.id===id)?.label||id;
 const syncMessage={guest:'この端末に保存します。別端末で使うには「表示・データ」でログインしてください。',syncing:'計画・診断を同期中…',synced:'計画・診断も同期済み。',pending:'計画・診断はこの端末に保存済み。同期待ちです。',conflict:'別端末の変更と競合しています。下で内容を選んでください。',rules:'計画・診断はこの端末に保存済み。クラウド同期の許可がありません。計画の前提に対応した最新版のルールを確認してください。',error:'計画・診断はこの端末に保存済み。同期できませんでした。接続後に再試行します。'};
 const statusHTML=()=>`<p class="small muted workspace-status" role="status">${esc(syncMessage[workspaceStatus]||syncMessage.guest)}${workspaceStatus==='rules'?' <a href="docs/firebase-setup.md#planning-rules">同期の設定手順</a>':''}</p>`;
 const conflicts=()=>documents.filter(r=>r.conflict).map(r=>`<section class="panel workspace-conflict"><h2>${r.kind==='planning'?'計画':'診断'}の変更が競合しています</h2><div class="conflict-comparison"><details><summary>この端末の内容</summary><pre>${r.kind==='diagnostic'?`${diagnosticSlots(r.payload).filter(s=>s.submitted).length} / 30問回答 · ${r.payload.status==='in_progress'?'診断中':'終了'}`:esc(JSON.stringify(r.payload,null,2))}</pre></details><details><summary>クラウドの内容</summary><pre>${r.kind==='diagnostic'?`${diagnosticSlots(r.conflict.payload).filter(s=>s.submitted).length} / 30問回答 · ${r.conflict.payload.status==='in_progress'?'診断中':'終了'}`:esc(JSON.stringify(r.conflict.payload,null,2))}</pre></details></div><div class="button-row"><button class="button secondary" data-action="workspace-remote" data-id="${esc(r.id)}">クラウドの内容を使う</button>${r.kind==='planning'?`<button class="button secondary" data-action="workspace-local" data-id="${esc(r.id)}">この端末の内容を使う</button>`:`<button class="button secondary" data-action="workspace-copy-run" data-id="${esc(r.id)}">この端末の診断を別の回として保存</button>`}</div></section>`).join('');
 const dateList=p=>p.examDates.length?`<ul class="plain-list">${p.examDates.map(d=>`<li><strong>${esc(partName(d.examPartId))}</strong> ${esc(d.date)}</li>`).join('')}</ul>`:'<p class="small muted">受験日は未登録です。</p>';
 const phaseList=(p,withActual=false,editable=withActual)=>p.phases.length?p.phases.map(item=>{const actual=withActual?progress.find(x=>x.id===item.id):null;return `<article class="plan-phase"><h3>${esc(item.name)}</h3><p class="small">${esc(item.start)} 〜 ${esc(item.end)} · ${esc(item.examPartIds.map(partName).join('・'))}</p><p><strong>${actual?`${actual.actual} / `:''}${item.targets.completedAttempts}回</strong>${actual?` · あと${actual.remaining}回`:''}</p>${item.focusTopicIds.length?`<p class="small">重点：${esc(item.focusTopicIds.map(id=>qualification.topics.find(t=>t.id===id)?.name||id).join('・'))}</p>`:''}${editable?`<div class="button-row"><button class="button secondary" data-action="edit-phase" data-id="${esc(item.id)}">編集</button><button class="button secondary" data-action="delete-phase" data-id="${esc(item.id)}" data-revision="${planRow.localRevision}">削除</button></div>`:''}${planTargetsHTML({phase:item,progress:actual,revision:planRow?.localRevision||0,parts,editingWeek,editingMilestone,readOnly:!editable})}</article>`;}).join(''):'<p class="small muted">フェーズは未登録です。</p>';
 const countdown=()=>{const next=upcomingExam(plan,qualification,new Date(),targetPartId);if(!next)return '';return `${esc(next.label)} · ${next.days>0?`試験まで${next.days}日`:next.days===0?'試験日です':`試験日から${-next.days}日`}`;};
 const focusNames=()=>phase?.focusTopicIds.map(id=>qualification.topics.find(t=>t.id===id)?.name||id).join('・')||'';
 const milestone=phase?.milestones?.filter(m=>!m.completed&&m.date>=dateInZone(new Date(),plan.timeZone)).sort((a,b)=>a.date.localeCompare(b.date))[0];
 const milestoneHTML=()=>milestone?`<p class="small plan-milestone"><strong>${esc(milestone.date)}：${esc(milestone.name)}</strong> · ${esc(partName(milestone.examPartId))}</p>`:'';
 function homeSupportHTML({nextTopic=null,resuming=false}={}){const next=upcomingExam(plan,qualification,new Date(),targetPartId),days=next?next.days>0?`試験まで${next.days}日`:next.days===0?'試験日です':`試験日から${-next.days}日`:'目標・計画';return `<section class="panel planning-entry compact-plan"><div class="heading-row"><h2>${next?`<span class="sr-only">${esc(next.label)} · </span>`:''}${days}</h2><button class="button secondary" data-view="planning">${planRow?'計画を見る':'計画を登録'}</button></div>${week?`<p class="small week-progress">今週 ${week.actual} / ${week.completedAttempts}回 · あと${week.remaining}回</p>`:phase?`<p class="small muted">この期間 ${phase.actual} / ${phase.targets.completedAttempts}回 · あと${phase.remaining}回</p>`:planRow?'<p class="small muted">現在の期間の計画はありません。</p>':'<p class="small muted">受験日・計画は、必要なときに登録できます。</p>'}${planRow&&nextTopic?`<p class="plan-next"><strong>今日：${esc(nextTopic)}${resuming?'の続き':'を1問'}</strong></p>`:''}${['rules','error','conflict','pending'].includes(workspaceStatus)?statusHTML():workspaceStatus==='guest'&&planRow?'<p class="small muted">この端末の計画です。</p>':''}</section>`;}
 function resumeHTML(){return active?`<section class="panel diagnostic-resume"><h2>診断を中断中</h2><p class="small">${diagnosticSlots(active.payload).filter(s=>s.submitted).length} / 30問に回答 · 支援なし</p><button class="button secondary" data-action="resume-diagnostic" data-id="${esc(active.id)}">診断の続きから</button></section>`:'';}
 function overviewHTML(){return `<section class="panel" id="plan-overview"><h2>${countdown()||'受験予定'}</h2>${dateList(plan)}${phase?`<p class="small muted">現在のフェーズ</p>${phaseList({...plan,phases:[phase]},true,false)}`:'<p class="muted">現在の期間の計画はありません。</p>'}<div class="button-row"><button class="button primary" data-action="start-session">とりあえずはじめる</button><button class="button secondary" data-action="open-editor">${planRow?'計画を編集する':'受験日・計画を登録する'}</button><button class="button secondary" data-action="open-ai">AIに相談・JSONを登録</button></div><details><summary>計画の前提・目標の数え方</summary>${contextHTML(plan.context)}<p class="small muted">実績は取り組み完了回数。解き直し・解答閲覧と、既存問題の完了診断を含みます。派生診断は含めません。予定の完了では回数は増えません。</p></details>${plan.phases.some(p=>p.id!==phase?.id)?`<details><summary>ほかの期間の計画</summary>${phaseList({...plan,phases:plan.phases.filter(p=>p.id!==phase?.id)},true,false)}</details>`:''}</section>`;}
 function editHTML(){const editing=plan.phases.find(p=>p.id===editingPhaseId),today=dateInZone(new Date(),plan.timeZone);return `<section class="panel"><h2>${esc(qualification.name)}</h2><form id="exam-form" data-revision="${planRow?.localRevision||0}">${parts.map(part=>`<label class="editor-field"><span>${esc(part.label)}の受験日（任意）</span><input type="date" name="exam-${esc(part.id)}" min="2000-01-01" max="2100-12-31" value="${esc(plan.examDates.find(d=>d.examPartId===part.id)?.date||'')}"></label>`).join('')}<p class="small muted">未登録でも学習できます。教材未対応のパートは日付のみ管理します。</p><button class="button secondary" type="submit">受験日を保存</button></form></section>
  ${contextFormHTML(plan,planRow?.localRevision||0)}
  <section class="panel"><div class="heading-row"><h2>期間ごとの計画</h2><button class="button secondary" data-action="export-plan">JSONを書き出す</button></div><p class="small muted">目標は解き直し・解答閲覧を含む取り組み回数。診断専用の派生問題は診断結果に分けます。1日休んでも、日々の未達を積み上げません。</p>${phaseList(plan,true)}<details ${editing?'open':''}><summary>${editing?'フェーズを編集':'フェーズを手動で追加'}</summary><form id="phase-form" data-revision="${planRow?.localRevision||0}" data-id="${esc(editing?.id||'')}"><label class="editor-field"><span>フェーズ名</span><input name="name" maxlength="80" required value="${esc(editing?.name||'')}" placeholder="例：基礎確認"></label><div class="form-pair"><label class="editor-field"><span>開始日</span><input name="start" type="date" required value="${esc(editing?.start||today)}"></label><label class="editor-field"><span>終了日</span><input name="end" type="date" required value="${esc(editing?.end||'')}"></label></div><label class="editor-field"><span>取り組み回数の目標</span><input name="target" type="number" min="1" max="100000" step="1" required value="${editing?.targets.completedAttempts||''}" placeholder="例：120"></label><fieldset class="plan-checks"><legend>対象パート</legend>${parts.filter(p=>p.practiceAvailable).map(p=>`<label><input type="checkbox" name="part" value="${esc(p.id)}" ${(editing?editing.examPartIds.includes(p.id):true)?'checked':''}>${esc(p.label)}</label>`).join('')}</fieldset><details><summary>重点分野を選ぶ（任意）</summary><fieldset class="plan-checks"><legend class="sr-only">重点分野</legend>${qualification.topics.map(t=>`<label><input type="checkbox" name="topic" value="${esc(t.id)}" ${editing?.focusTopicIds.includes(t.id)?'checked':''}>${esc(t.name)}</label>`).join('')}</fieldset></details><p class="small muted">重点以外の分野も、対象パート内なら実績に数えます。</p><div class="button-row"><button type="submit" class="button primary">${editing?'変更を保存':'フェーズを追加'}</button>${editing?'<button type="button" class="button secondary" data-action="cancel-phase">編集をやめる</button>':''}</div></form></details></section>`;}
 function aiHTML(){return `<section class="panel"><h2>AIに学習計画を相談</h2><p class="small">学習状況と対応フォーマットをコピーし、使っているAIへ貼り付けます。AIへの接続・課金はありません。</p>${summaryData?summaryPreviewHTML(summaryData,parts):''}<div class="button-row"><button class="button secondary" data-action="copy-prompt">AI用プロンプトをコピー</button><button class="button secondary" data-action="copy-summary">学習状況JSONをコピー</button><button class="button secondary" data-action="export-summary">学習状況を書き出す</button></div><p class="small"><a href="docs/study-plan-format.md">公開フォーマット</a> · <a href="schemas/study-plan.v1.json">JSON Schema</a></p><label class="editor-field"><span>AIが作った計画JSON</span><textarea id="plan-json" rows="8" maxlength="262144" placeholder="計画JSONを貼り付けてください">${esc(jsonInput)}</textarea></label><button class="button secondary" data-action="preview-plan">検証してプレビュー</button><div id="plan-preview">${preview?`<section class="plan-preview"><h3>登録後の内容</h3><p class="small">現在の受験日・計画を置き換えます。学習記録は変更しません。</p>${dateList(preview)}<h4>計画の前提</h4>${contextHTML(preview.context)}${phaseList(preview)}<button class="button primary" data-action="register-plan">この内容で登録</button></section>`:''}</div></section>`;}
 function planningHTML(){return `<div class="page-heading"><h1>受験日・学習計画</h1><button class="button study-back-button" data-view="home"><span aria-hidden="true">⌂</span> ホーム</button></div>${statusHTML()}<div id="workspace-conflicts">${conflicts()}</div><div class="notice" id="planning-stale" hidden><p>別端末・別タブの変更があります。入力中の内容はそのまま残しています。</p><button class="button secondary" data-action="reload-planning">入力を破棄して最新版を表示</button></div>${overviewHTML()}<details class="plan-editor" id="plan-editor" ${editorOpen?'open':''}><summary>受験日・計画を編集する</summary>${editHTML()}</details><details class="plan-ai" id="plan-ai" ${aiOpen?'open':''}><summary>AIに相談・JSONを登録する</summary>${aiHTML()}</details>`;}
 function diagnosticsHTML(){return `<div class="page-heading"><h1>実力診断</h1><button class="button study-back-button" data-view="home"><span aria-hidden="true">⌂</span> ホーム</button></div>${statusHTML()}${conflicts()}${runs.filter(r=>r.payload.status==='in_progress').length>1?`<section class="panel"><h2>中断中の診断</h2>${runs.filter(r=>r.payload.status==='in_progress').map(r=>`<div class="row"><p>${dateText(r.payload.startedAt)} · ${Object.keys(r.payload.responses).length} / 30問確定</p><button class="button secondary" data-action="resume-diagnostic" data-id="${esc(r.id)}">この診断を再開</button></div>`).join('')}</section>`:''}<section class="panel"><h2>30問で確認</h2><p>複数分野から出題します。ヒント・解答閲覧はなく、正誤と解説は終了後に確認します。</p><p class="small muted">中断・再開できます。分野別の回答数を添えて結果を表示します。通常学習に診断は必須ではありません。現在の診断専用派生問題は${qualification.diagnostic?.count||0}問。分野配分を保ち、不足は既存過去問で補います。</p><button class="button primary" data-action="${active?'resume-diagnostic':'start-diagnostic'}" ${active?`data-id="${esc(active.id)}"`:''}>${active?'診断の続きから':'30問の診断をはじめる'}</button></section><section class="panel"><div class="heading-row"><h2>過去の診断</h2><button class="button secondary" data-action="export-diagnostics">診断を書き出す</button></div><label class="button secondary file-label">診断を取り込む<input type="file" id="import-diagnostics" accept="application/json,.json"></label>${finished.length?finished.map(r=>{const result=diagnosticResult(r.payload,qualification);return `<div class="row"><div><p>${dateText(r.payload.completedAt)} · ${result.answered} / 30問回答${r.payload.status==='ended_early'?' · 部分結果':''}</p><p class="small">正解${result.correct}・不正解${result.incorrect}・未回答${result.unanswered}</p></div><button class="button secondary" data-action="resume-diagnostic" data-id="${esc(r.id)}">結果を見る</button></div>`;}).join(''):'<p class="empty">まだ診断していません。</p>'}</section>`;}
 function diagnosticHTML(){
  if(!run)return diagnosticsHTML();
  if(runRow.conflict)return `<div class="page-heading"><h1>診断の変更が競合しています</h1></div>${conflicts()}`;
  if(run.status!=='in_progress')return resultHTML();
  const slot=diagnosticSlots(run)[run.currentIndex],q=slot.attempt.questionSnapshot,last=run.currentIndex===29;
  return `<div class="study-toolbar"><button class="button study-back-button" data-action="pause-diagnostic"><span aria-hidden="true">Ⅱ</span> 中断</button><p class="page-note">診断 ${run.currentIndex+1} / 30問</p></div><article class="panel question-panel diagnostic-question"><div class="question-meta"><span class="badge">${esc(q.topic)}</span><span>${esc(q.packLabel)} · 問${q.number}${q.diagnosticOnly?' · 診断専用の独自問題':''}</span></div>${q.stem?`<p class="question-stem">${esc(q.stem)}</p>`:q.sourceImages.map((url,i)=>`<figure class="source-question"><img src="${esc(url)}" alt="${esc(q.imageAlt||q.title)}${q.sourceImages.length>1?'（'+(i+1)+'）':''}" loading="eager"><button class="button secondary" data-action="diagnostic-zoom" data-index="${i}">問題を拡大</button></figure>`).join('')}${q.image?`<figure class="question-figure"><img src="${esc(q.image)}" alt="${esc(q.imageAlt||'問題の図')}"></figure>`:''}<fieldset class="choices"><legend class="sr-only">診断の選択肢</legend>${q.choices.map(c=>`<label class="choice ${slot.selectedChoiceId===c.id?'selected':''}"><input type="radio" name="diagnostic-answer" value="${esc(c.id)}" ${slot.selectedChoiceId===c.id?'checked':''}><span class="choice-code">${esc(c.label)}</span><span class="choice-text">${esc(c.text||'')}${c.image?`<img src="${esc(c.image)}" alt="選択肢${esc(c.label)}の図">`:''}</span></label>`).join('')}</fieldset><div class="button-row"><button class="button primary" data-action="submit-diagnostic" ${slot.selectedChoiceId===null?'disabled':''}>${last?'回答して結果へ':'回答して次へ'}</button><button class="button secondary" data-action="skip-diagnostic">未回答で次へ</button></div></article><button class="button secondary" data-action="end-diagnostic">ここまでで診断終了</button>`;
 }
 function resultHTML(){
  const result=diagnosticResult(run,qualification),derived=diagnosticAttempts(run),byId=new Map(derived.map(a=>[a.id,a]));
  return `<div class="page-heading"><h1>診断結果${run.status==='ended_early'?'（部分結果）':''}</h1><button class="button study-back-button" data-view="home"><span aria-hidden="true">⌂</span> ホーム</button></div><section class="panel"><h2>${result.answered} / 30問に回答</h2><p class="diagnostic-counts"><strong>正解 ${result.correct}</strong> · 不正解 ${result.incorrect} · 未回答 ${result.unanswered}</p><p>回答した${result.answered}問の正答率：${result.correctRate===null?'未確認':Math.round(result.correctRate*100)+'%'}</p><p class="small muted">支援なし。既に取り組んだ問題 ${result.previouslySeen}問。今回の回答から、次に確認する分野を選べます。既出はアプリ内の履歴のみです。</p><details><summary>出題構成を確認</summary><ul>${result.composition.map(c=>`<li>${c.kind==='derived'?'派生問題':'既存過去問'}：${c.selected}問出題・${c.answered}問回答・${c.correct}問正解・既出${c.previouslySeen}問${c.kind==='derived'?`（元問題の履歴あり${c.parentPreviouslySeen}問）`:''}</li>`).join('')}</ul><p class="small muted">出題方針：版${result.blueprintVersion}。構成や難易度が異なる診断の正答率だけで、実力の変化を断定しません。</p></details><div class="diagnostic-topics">${result.topics.map(t=>`<div class="row"><div><strong>${esc(t.label)}</strong><p class="small">${t.answered?`${t.answered}問回答中${t.correct}問正解`:'未確認'}</p></div><button class="button secondary" data-action="topic-session" data-topic="${esc(t.label)}">この分野を学習</button></div>`).join('')}</div><p class="small muted">分野全体の習熟・合格可能性は断定しません。</p></section><section class="panel"><h2>回答と解説</h2>${diagnosticSlots(run).map((s,i)=>{const a=byId.get(s.id),q=s.attempt.questionSnapshot,m=s.attempt.materialSnapshot;return `<details class="diagnostic-review" data-diagnostic-slot="${esc(s.id)}"><summary>${i+1}. ${esc(q.topic)} · ${a?a.status==='correct'?'正解':'不正解':'未回答'}</summary><p class="small">${esc(q.packLabel)} · 問${q.number}</p><p>あなたの回答：${esc(s.submitted?q.choices.find(c=>c.id===s.selectedChoiceId)?.label||'未回答':'未回答')} · 正解：${esc(q.choices[q.answer].label)}</p><p class="explanation">${esc(m.summary)}</p><p class="explanation">${esc(m.explanation)}</p><ul class="reason-list">${m.choiceReasons.map((reason,j)=>`<li><b>${esc(q.choices[j].label)}</b>${esc(reason)}</li>`).join('')}</ul><button class="button secondary" data-action="start" data-id="${esc(q.diagnosticOnly?q.parentQuestionId:q.id)}">${q.diagnosticOnly?'元の過去問を学習':'学習モードで解き直す'}</button></details>`;}).join('')}</section><div class="button-row"><button class="button secondary" data-view="planning" data-open-ai="true">結果と学習状況をAIへ渡す</button><button class="button secondary" data-view="diagnostics">診断の一覧へ</button></div>`;
 }
 return {timeZone:plan.timeZone,homeSupportHTML,resumeHTML,planningHTML,diagnosticsHTML,diagnosticHTML,statusHTML,conflictsHTML:conflicts,overviewHTML,summaryHTML:()=>summaryData?summaryPreviewHTML(summaryData,parts):''};
}
