import {esc} from '../utils.js';
import {addDays} from '../domain/planning.js';

// A phase owns its week targets and manual milestones. Preview uses the same
// labels but exposes no editing or completion controls.
export function planTargetsHTML({phase,progress,revision=0,parts,editingWeek,editingMilestone,readOnly=false}){
 const weeks=[...(phase.weeklyTargets||[])].sort((a,b)=>a.start.localeCompare(b.start));
 const milestones=[...(phase.milestones||[])].sort((a,b)=>a.date.localeCompare(b.date));
 const week=weeks.find(w=>editingWeek?.phaseId===phase.id&&w.id===editingWeek.id);
 const milestone=milestones.find(m=>editingMilestone?.phaseId===phase.id&&m.id===editingMilestone.id);
 const data=item=>`data-phase="${esc(phase.id)}" data-id="${esc(item.id)}" data-revision="${revision}"`;
 const partName=id=>parts.find(p=>p.id===id)?.label||id;
 const weeksHTML=weeks.map(w=>{const actual=progress?.weeklyProgress.find(p=>p.id===w.id);return `<div class="plan-target-row"><div><p>${esc(w.start)} 〜 ${esc(w.end)}</p><p><strong>${w.completedAttempts}回予定${actual?` / 現在${actual.actual}回 / あと${actual.remaining}回`:''}</strong></p></div>${readOnly?'':`<div class="button-row"><button class="button secondary" data-action="edit-week" ${data(w)}>週別目標を編集</button><button class="button secondary" data-action="delete-week" ${data(w)}>週別目標を削除</button></div>`}</div>`;}).join('');
 const milestonesHTML=milestones.map(m=>`<div class="plan-target-row"><div><p><strong>${esc(m.name)}</strong> ${m.completed?'<span class="badge">完了</span>':''}</p><p class="small">${esc(m.date)} · ${esc(partName(m.examPartId))}</p></div>${readOnly?'':`<div class="button-row"><button class="button secondary" data-action="toggle-milestone" ${data(m)}>${m.completed?'未完了に戻す':'完了にする'}</button><button class="button secondary" data-action="edit-milestone" ${data(m)}>予定を編集</button><button class="button secondary" data-action="delete-milestone" ${data(m)}>予定を削除</button></div>`}</div>`).join('');
 if(readOnly)return `${weeks.length?`<h4>週別目標</h4>${weeksHTML}`:''}${milestones.length?`<h4>予定</h4>${milestonesHTML}`:''}`;
 const start=week?.start||phase.start,end=week?.end||[addDays(start,6),phase.end].sort()[0];
 return `<details class="phase-targets" ${week||milestone?'open':''}><summary>週別目標・予定${weeks.length||milestones.length?`（目標${weeks.length}件・予定${milestones.length}件）`:''}</summary><h4>週別目標</h4><p class="small muted">1〜7日の区切りを登録できます。フェーズの対象パートで数え、未達を次週へ自動で足しません。</p>${weeksHTML||'<p class="small muted">週別目標は未登録です。</p>'}<details ${week?'open':''}><summary>${week?'週別目標を編集':'週別目標を追加'}</summary><form data-planning-form="week" data-phase="${esc(phase.id)}" data-id="${esc(week?.id||'')}" data-revision="${revision}"><div class="form-pair"><label class="editor-field"><span>週の開始日</span><input name="start" type="date" min="${esc(phase.start)}" max="${esc(phase.end)}" value="${esc(start)}" required></label><label class="editor-field"><span>週の終了日</span><input name="end" type="date" min="${esc(phase.start)}" max="${esc(phase.end)}" value="${esc(end)}" required></label></div><label class="editor-field"><span>週の目標回数</span><input name="target" type="number" min="1" max="100000" step="1" value="${week?.completedAttempts||''}" placeholder="例：70" required></label><div class="button-row"><button class="button secondary" type="submit">週別目標を保存</button>${week?'<button class="button secondary" type="button" data-action="cancel-week">週の編集をやめる</button>':''}</div></form></details><h4>予定</h4><p class="small muted">模試・読書・直前復習など。完了は自分で付けます。問題数の実績は増えません。</p>${milestonesHTML||'<p class="small muted">予定は未登録です。</p>'}<details ${milestone?'open':''}><summary>${milestone?'予定を編集':'予定を追加'}</summary><form data-planning-form="milestone" data-phase="${esc(phase.id)}" data-id="${esc(milestone?.id||'')}" data-revision="${revision}"><label class="editor-field"><span>予定の名前</span><input name="name" maxlength="80" value="${esc(milestone?.name||'')}" placeholder="例：手元の教材で模試" required></label><label class="editor-field"><span>予定日</span><input name="date" type="date" min="${esc(phase.start)}" max="${esc(phase.end)}" value="${esc(milestone?.date||phase.end)}" required></label><label class="editor-field"><span>予定のパート</span><select name="part">${parts.map(p=>`<option value="${esc(p.id)}" ${(milestone?.examPartId||phase.examPartIds[0])===p.id?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label><div class="button-row"><button class="button secondary" type="submit">予定を保存</button>${milestone?'<button class="button secondary" type="button" data-action="cancel-milestone">予定の編集をやめる</button>':''}</div></form></details></details>`;
}
