import {imageZoomCue} from './image-zoom.js';
import {fieldBar,fieldLegend} from './field-progress.js';
import {examPartsFor,dateInZone,addDays} from '../domain/planning.js';
import {esc, now, dateText, timeText} from '../utils.js';
import {complete, labels, enriched, hintKind, hintTotal} from '../domain/study.js';

// Render from a snapshot of the current context; this module does not save or navigate.
export function createViews(context) {
 const {state, workspaceViews, base, catalog, PAGE_SIZE, examLabel, question, current, reviewInfo, reviewQuestions, topics, topicPool, latest, previousAttempt, improvement, sessionCount, hasFreshTopicQuestion, materialUpdateAvailable, qualification, readNote} = context;
 const {cardsEnabled,recommendation,homeTopicPool,entryActions,studyContext,contextLabel,homeFields,nextAction,fieldData,fieldMode,fieldPartId,diagnosis,normalAttempts}=context;
 const activeQuestionIds=new Set(base.map(q=>q.id)),continuedParents=new Set(state.attempts.map(a=>a.continuationOf).filter(Boolean));
 const timeZone=workspaceViews?.timeZone||qualification.timeZone||'Asia/Tokyo',at=now(),todayKey=dateInZone(at,timeZone),completed=state.attempts.filter(a=>complete(a)&&Date.parse(a.completedAt)<=Date.parse(at));
function badge(a) { return `<span class="badge ${a.status==='correct'?'good':a.status==='incorrect'?'wrong':complete(a)?'help':''}">${labels[a.status]}</span>`; }
function rowHTML(q, info, action = 'start', label='解く') {
  return `<div class="row"><div><p class="row-title">${esc(q.title)}</p><p class="row-meta">${examLabel(q)} · 問${q.number} · ${esc(q.topic)}</p>${state.settings.paperMode==='paperless'?`<p class="small muted">${esc(contextLabel(q))}</p>`:''}${info?`<div class="history-result">${badge(info.a)}<span class="small muted">解答前のヒント ${info.a.hintsBeforeAnswer}/${hintTotal(info.a)}</span></div>`:''}</div><div class="row-actions"><button class="button secondary" data-action="${action}" data-id="${q.id}">${label}</button></div></div>`;
}
function paperModeHTML(){return qualification.studyContext?`<div class="study-mode" role="group" aria-label="取り組み方"><button class="button secondary" data-action="paper-mode" data-mode="all" aria-pressed="${state.settings.paperMode==='all'}">すべて</button><button class="button secondary" data-action="paper-mode" data-mode="paperless" aria-pressed="${state.settings.paperMode==='paperless'}">紙・ペンなし</button><button class="button secondary" data-action="paper-mode" data-mode="desk" aria-pressed="${state.settings.paperMode==='desk'}">書いて考える</button></div>${state.settings.paperMode==='paperless'?`<p class="small start-note">原本確認済みの${qualification.studyContext.paperless}問から選びます。</p>`:''}`:'';}
function homeHTML() {
 const q=nextAction.questionId?question(nextAction.questionId):null,reviews=reviewQuestions();
 const names={paperless:'身軽に1問',desk:'書いて考える1問',all:'おまかせで1問'};
 const entrances=Object.entries(entryActions).map(([mode,a])=>{const selected=mode===state.settings.lastEntry,resume=a.kind==='resume',disabled=a.kind==='unavailable';return `<button class="button study-entrance ${selected?'primary':'secondary'}" data-action="${resume?'entry-resume':'entry-start'}" data-paper-mode="${mode}" data-id="${esc(resume?a.attemptId:a.questionId||'')}" data-topic-id="${esc(a.scope?.topicId||'')}" data-part-id="${esc(a.scope?.examPartId||'')}" ${disabled?'disabled':''} ${selected?'data-last-entry="true"':''}${disabled?` title="${esc(a.reason)}"`:''}><span>${names[mode]}</span><span class="entry-cue">${resume?'続きから ':''}<span aria-hidden="true">→</span></span></button>`;}).join('');
 const candidates=[...homeFields.rows.filter(r=>r.focus),...homeFields.rows.filter(r=>r.total)],quickTopics=candidates.filter((r,i)=>candidates.findIndex(x=>x.topicId===r.topicId)===i&&homeTopicPool(r.label,r.topicId).length).slice(0,2);
 const focus=homeFields.rows.filter(r=>r.total&&(r.focus||reviews.some(x=>x.q.topicId===r.topicId&&x.info.isDue))).slice(0,2);
 const today=normalAttempts.filter(a=>complete(a)&&Date.parse(a.completedAt)<=Date.parse(at)&&dateInZone(a.completedAt,timeZone)===todayKey).length;
 return `<div class="home-core"><section class="panel quick-start-panel hero-start"><h1 class="entry-heading">とりあえずはじめる</h1><div class="quick-start entry-list">${entrances}</div>${Object.values(entryActions).every(a=>a.kind==='unavailable')?`<p class="small start-note">${esc(nextAction.reason)}</p>`:''}</section>
 <section class="panel home-shortcuts" aria-label="単語帳と分野別演習"><div class="button-row">${cardsEnabled&&qualification.flashcards?.count?`<button class="button secondary" data-action="cards-open">単語帳 · ${qualification.flashcards.count}枚</button>`:''}<button class="button secondary" data-view="topics" data-paper-mode="${state.settings.lastEntry}">分野別に解く</button></div>${quickTopics.length?`<div class="button-row quick-topics">${quickTopics.map(r=>`<button class="button secondary" data-action="topic-session" data-topic="${esc(r.label)}" data-paper-mode="${state.settings.lastEntry}">${esc(r.label)}</button>`).join('')}</div>`:''}</section>
 ${workspaceViews?.homeSupportHTML({nextTopic:recommendation?.kind==='question'?question(recommendation.questionId)?.topic:q?.topic,resuming:!recommendation&&nextAction.kind==='resume',planRecommendation:recommendation?.kind==='question',paperMode:state.settings.lastEntry})||''}</div>
 <div class="button-row home-tools"><button class="button secondary" data-view="review">解き直し${reviews.length?' · '+reviews.length+'問':''}</button><button class="button secondary" data-view="diagnostics">${diagnosis?'診断結果を見る':'実力診断（30問）'}</button></div>${workspaceViews?.resumeHTML()||''}
 ${focus.length?`<section class="panel field-suggestions"><div class="heading-row"><h2>次に確認する分野</h2><button class="button secondary" data-view="topics">全分野を見る</button></div>${focus.map(r=>`<div class="field-suggestion"><div class="heading-row"><strong>${esc(r.label)}</strong><span class="small">${r.focus?'計画の重点':'復習日'}</span></div>${fieldBar(r)}<button class="button secondary" data-action="field-focus" data-topic-id="${esc(r.topicId)}">この分野の記録を見る</button></div>`).join('')}</section>`:''}
 ${state.settings.deskQuestionIds.length?`<details class="desk-preferences home-options"><summary>自分の机指定 ${state.settings.deskQuestionIds.length}問</summary><p class="small">指定を解除すると、原本確認済みの候補は再び身軽に1問で出題します。回答記録は保持します。</p><button class="button secondary" data-action="clear-desk">机指定を解除</button></details>`:''}<p class="small muted today-progress">今日 ${today}回 · <button class="button secondary" data-view="history">記録を見る</button></p>`;
}
function topicsHTML() {
 const diag=fieldMode==='diagnostic',parts=examPartsFor(qualification),data=fieldData;
 return `<div class="page-heading"><h1>分野別演習</h1><button class="button secondary" data-view="materials">問題を探す</button></div><section class="panel field-overview">${paperModeHTML()}${cardsEnabled&&qualification.flashcards?.count?'<p><button class="button secondary" data-action="cards-open">単語帳を開く</button></p>':''}<div class="button-row field-tabs" role="group" aria-label="分野の記録の種類"><button class="button secondary" data-action="field-mode" data-mode="learning" aria-pressed="${!diag}">普段の学習・直近28日</button><button class="button secondary" data-action="field-mode" data-mode="diagnostic" aria-pressed="${diag}">最新の30問診断</button></div>${diag?diagnosis?`<p>${dateText(diagnosis.completedAt)} · ${diagnosis.answered} / ${diagnosis.size}問に回答 · ${diagnosis.correct}問正解</p><p class="small muted">支援なし。未回答${diagnosis.unanswered}問・既出${diagnosis.previouslySeen}問。1回の結果です。</p>`:'<p class="empty">完了した診断はありません。通常学習はそのまま始められます。</p>':`<p class="small muted">同じ問題は最後の1記録。途中・診断は含めません。割合だけで習熟・合格は判断しません。</p>${parts.filter(p=>p.practiceAvailable).length>1?`<label class="field-part">対象パート <select name="field-part"><option value="">全パート</option>${parts.filter(p=>p.practiceAvailable).map(p=>`<option value="${esc(p.id)}" ${fieldPartId===p.id?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label>`:''}`}${fieldLegend(diag)}<details><summary>グラフの数え方</summary><p class="small muted">通常：直近28日の問題ごとの最後の完了記録。自力正解÷（自力・ヒント付き正解・不正解・解答閲覧）。診断：この1回の正解÷回答確定数。記録なしは0%ではなく未確認。10問未満は記録少なめの目印で、確定した苦手判定ではありません。計画実績の取り組み回数や、AI出力の全試行の率とは別の集計です。</p></details></section>
 <div class="topic-grid">${data.rows.map(row=>{
  const topic=qualification.topics.find(t=>t.id===row.topicId)?.name||row.label,pool=topicPool(topic,row.topicId,diag?null:fieldPartId),description=base.find(q=>q.topicId===row.topicId);
  return `<section class="panel topic-card" id="field-${esc(row.topicId)}"><div class="heading-row"><h2>${esc(topic)}</h2>${row.focus?'<span class="badge">計画の重点</span>':`<span class="badge">${pool.length}問</span>`}</div>${fieldBar(row,{diagnostic:diag})}<div class="button-row topic-actions"><button class="button secondary" data-action="topic-session" data-topic="${esc(topic)}" data-part-id="${esc(diag?'':fieldPartId||'')}" ${pool.length?'':'disabled'}>この分野をはじめる</button></div><details class="reading-note"><summary>教科書メモ（任意）</summary><label class="editor-field"><span>章・ページ</span><input type="text" maxlength="200" data-reading-topic="${esc(topic)}" aria-label="${esc(topic)}で読んだ範囲" placeholder="例：第3章、p.40〜48" value="${esc(readNote(topic))}"></label>${description?`<p class="small muted">${esc(description.topicDescription||description.concept||'')}</p>`:''}</details></section>`;
 }).join('')}</div><p class="page-note">${state.settings.paperMode==='paperless'?'紙・ペンなしの候補だけを開始します。分野グラフは通常の全記録です。 ':''}${base.length}問・${qualification.topics.length}分野。分野はアプリ独自の分類です。選んだ分野を1問ずつ続けられます。</p>`;
}
function progressFeedbackHTML(a) { const message=improvement(a);return message?`<p class="progress-feedback">${esc(message)}</p>`:''; }
function achievements() {
  const done=completed;
  const unique=new Set(done.map(a=>a.questionId)).size;
  const days=new Set(done.map(a=>dateInZone(a.completedAt,timeZone))).size;
  const recovered=done.some(a=>a.status==='correct'&&!a.confidence&&previousAttempt(a)?.status==='incorrect');
  return [
    {title:'1問に解答',detail:'1問に取り組む',earned:done.length>=1},
    {title:'3種類の問題に解答',detail:'違う3問に取り組む',earned:unique>=3},
    {title:'不正解を解き直して正解',detail:'不正解の問題を、ヒントなしで正解',earned:recovered},
    {title:'2日以上学習',detail:'2日以上、問題に取り組む',earned:days>=2}
  ];
}
function motivationHTML() {
  const done=completed;
  const today=done.filter(a=>dateInZone(a.completedAt,timeZone)===todayKey);
  const unique=new Set(done.filter(a=>activeQuestionIds.has(a.questionId)).map(a=>a.questionId)).size;
  const awards=achievements();const earned=awards.filter(a=>a.earned);const next=awards.find(a=>!a.earned);
  const recent=done.slice().reverse().find(a=>improvement(a));
  const dates=Array.from({length:7},(_,i)=>addDays(todayKey,i-6));
  const active=dates.filter(d=>done.some(a=>dateInZone(a.completedAt,timeZone)===d)).length;
  return `<section class="panel motivation-panel"><div class="heading-row"><h2>学習状況</h2><span class="badge ${today.length?'good':''}">${today.length?'✓ ':''}今日 ${today.length}問</span></div><p class="progress-counts">解答済み ${unique} / ${base.length}問・${done.length}回<span>直近7日 ${active}日</span></p>${recent?`<p class="progress-feedback">${esc(question(recent.questionId).title)}：${esc(improvement(recent))}</p>`:''}<details class="achievements"><summary>学習日・達成 ${earned.length} / 4</summary><div class="week-calendar" aria-label="この7日間の問題への取り組み">${dates.map(d=>{const count=done.filter(a=>dateInZone(a.completedAt,timeZone)===d).length;return `<div class="calendar-day ${count?'studied':''} ${d===todayKey?'today':''}" aria-label="${new Date(d).toLocaleDateString('ja-JP',{timeZone:'UTC',month:'long',day:'numeric'})}、${count}問に取り組みました"><span>${new Date(d).toLocaleDateString('ja-JP',{timeZone:'UTC',weekday:'short'})}</span><strong>${count?'✓':'・'}</strong><small>${Number(d.slice(-2))}日</small></div>`;}).join('')}</div><div class="achievement-list">${earned.map(a=>`<div class="achievement"><span aria-hidden="true">✓</span><strong>${a.title}</strong></div>`).join('')}${next?`<p class="page-note">次の達成：${next.detail}</p>`:''}</div></details></section>`;
}
function studyHTML() {
  const a=current(); const original=a.questionSnapshot||question(a.questionId); const q={...original,...a.materialSnapshot,choiceReasons:a.materialSnapshot.choiceReasons || [],hintStatus:hintKind(a.materialSnapshot)}; const answered=complete(a);
  const count=sessionCount();
  return `<div class="study-toolbar"><button class="button study-back-button" data-action="pause">${!answered?'<svg class="study-back-icon" viewBox="0 0 20 20" width="18" height="18" aria-hidden="true"><rect x="4" y="3" width="4" height="14" rx="1" fill="currentColor"/><rect x="12" y="3" width="4" height="14" rx="1" fill="currentColor"/></svg>':'<svg class="study-back-icon" viewBox="0 0 20 20" width="18" height="18" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M2.5 9 10 3l7.5 6M5 7v10h4v-5h2v5h4V7"/></svg>'}${answered?'ホーム':'中断'}</button>${!answered&&state.session.intent==='direct'?`<button class="button secondary" data-action="direct-return">${state.session.returnView==='flashcards'?'単語帳に戻る':state.session.returnView==='study'?'元の学習に戻る':'元の画面に戻る'}</button>`:''}<p class="page-note">${state.session.intent==='review'?'復習 · ':state.session.topic?esc(state.session.topic)+'のみ · ':state.session.topicIds?.length?'計画の重点 · ':''}今回 ${count}問</p></div><article class="panel question-panel"><div class="question-meta"><span class="badge">${esc(q.topic)}</span><span>${examLabel(q)} · 問${q.number}</span></div>${a.readingNote?`<p class="reading-context small">読んだ範囲：${esc(a.readingNote)}</p>`:''}<h1 class="sr-only">${esc(q.title)}</h1>${q.stem?`<p class="question-stem">${esc(q.stem)}</p>`:sourceImagesHTML(q)}
  ${q.image?`<figure class="question-figure"><a class="figure-link image-zoom-target" href="${esc(q.image)}" target="_blank" rel="noopener" aria-label="問題の図を拡大（別タブで開く）"><img src="${esc(q.image)}" alt="${esc(q.imageAlt)}">${imageZoomCue}</a></figure>`:''}
  <fieldset class="choices"><legend>${answered?'選択と正解':'答えを1つ選んでください'}</legend>${q.choices.map((c,i)=>`<label class="choice ${a.selected===i?'selected':''} ${answered&&q.answer===i?'correct-choice':''} ${answered&&a.selected===i&&q.answer!==i?'wrong-choice':''}"><input type="radio" name="answer" value="${i}" ${a.selected===i?'checked':''} ${answered?'disabled':''}><span class="choice-code">${esc(c.label)}</span>${c.text||c.image?`<span class="choice-text">${c.image?`<img src="${c.image}" alt="${esc(c.text)}">`:''}${esc(c.text)}</span>`:''}${answered&&q.answer===i?'<span class="sr-only">（正解）</span>':''}${answered&&a.selected===i?'<span class="sr-only">（あなたの回答）</span>':''}</label>`).join('')}</fieldset>
  ${answered?`<div class="answer-selection" aria-label="あなたの回答と正解"><span>あなたの回答：<strong>${a.selected===null?'未回答':esc(q.choices[a.selected].label)}</strong></span><span>正解：<strong>${esc(q.choices[q.answer].label)}</strong></span></div>`:''}
  ${!answered?`<label class="confidence"><input id="confidence" type="checkbox" ${a.confidence?'checked':''}>自信がないので、正解でも解き直したい</label>`:''}
  <section class="hint-section" aria-label="段階的なヒント">${materialUpdateAvailable(a)?`<div class="hint-update"><p class="page-note">${hintKind(a.materialSnapshot)==='topic-guide'?'以前の分野共通ガイドが保存されています。':'この記録には更新前の教材が保存されています。'}</p><button class="button secondary" data-action="latest-hints">最新のヒントで${answered?'解き直す':'続ける'}</button></div>`:''}<div class="hint-head"><h3>${hintKind(q)==='individual'?'ヒント':'考える手順（分野共通）'}</h3><span class="hint-count">${a.hintCount} / ${q.hints.length}</span></div><div id="hints" aria-live="polite">${q.hints.slice(0,a.hintCount).map((h,i)=>`<div class="hint-box" tabindex="-1"><h4>${i+1}. ${esc(h.title)}${h.revealsAnswer?'（答えを含む）':''}</h4><p>${esc(h.text)}</p></div>`).join('')}</div>${a.hintCount<q.hints.length?`<button class="button secondary" style="margin-top:14px" data-action="hint">${a.hintCount?'次のヒントを見る':'ヒントを1つ見る'}${q.hints[a.hintCount].revealsAnswer?'（答えを含む）':''}</button>`:`<p class="page-note" style="margin-top:12px">全ヒントを表示済み。</p>`}${answered?'<p class="page-note" style="margin-top:10px">解答後のヒント閲覧は、解答前の記録に加えません。</p>':''}</section>
  ${answered?resultHTML(q,a):`<div class="answer-actions"><button class="button primary" data-action="submit" ${a.selected===null?'disabled':''}>回答する</button><button class="button quiet" data-action="reveal">解答を見る</button></div><button class="button quiet" style="margin-top:8px" data-action="postpone">この問題はあとで解く</button>`}
  <details class="source-details"><summary>問題の出典と教材について</summary><p>出典：${esc(q.source)}</p><p>${esc(q.adaptation)} 学習ガイド・個別ヒントと解説は独自作成です。${esc(qualification.sourceLabel)}の公式解説ではありません。</p><div class="link-list">${q.questionUrl?`<a href="${esc(q.questionUrl)}${q.page?'#page='+q.page:''}" target="_blank" rel="noopener">${esc(qualification.questionLinkLabel||'問題の出典')}</a>`:''}${q.answerUrl?`<a href="${esc(q.answerUrl)}" target="_blank" rel="noopener">${esc(qualification.answerLinkLabel||'解答の出典')}</a>`:''}</div></details></article>${!answered&&(state.session.paperMode||state.settings.paperMode)==='paperless'?'<div class="study-options"><button class="button secondary paper-required" data-action="desk-later">この問題は紙ペンが必要</button><p class="small muted">今後の「身軽に1問」から外して中断します。回答候補・ヒントは残り、「書いて考える1問」で再開できます。</p></div>':''}`;
}
function resultHTML(q,a) {
  const info=reviewInfo(q);
  return `<section class="result" id="result" aria-label="解答と解説"><h2 id="result-heading" tabindex="-1">${labels[a.status]}</h2>${progressFeedbackHTML(a)}<p><strong>正解：${esc(q.choices[q.answer].label)}</strong> <span class="small muted">· 解答前のヒント ${a.hintsBeforeAnswer}/${hintTotal(a)}${a.confidence?' · 自信なし':''}</span></p>${!enriched(q)?`<p class="page-note">個別の解答解説は未追加です。正解は${esc(qualification.sourceLabel)}の解答と照合済みです。</p>`:''}<p class="explanation">${esc(q.summary)}</p>${enriched(q)&&a.selected!==null&&a.selected!==q.answer&&q.choiceReasons[a.selected]?`<p class="explanation"><strong>選択肢${esc(q.choices[a.selected].label)}の理由</strong><br>${esc(q.choiceReasons[a.selected])}</p>`:''}<details ${a.status==='incorrect'||a.status==='revealed'?'open':''}><summary>${enriched(q)?'解説':'分野の復習メモ'}</summary><p class="explanation">${esc(q.explanation)}</p></details>${q.choiceReasons.length?`<details><summary>選択肢ごとの解説</summary><ul class="reason-list">${q.choiceReasons.map((r,i)=>`<li><b>${esc(q.choices[i].label)}</b>${esc(r)}</li>`).join('')}</ul></details>`:''}<p class="takeaway"><strong>要点</strong>${esc(q.takeaway)}</p><p class="review-date">次の復習目安：${esc(info.dueDate||dateText(info.due))}<br><span class="small">${info.needs?'翌日が復習目安です。':'別の日の自力正解：'+info.successes+'回。'}</span></p>${q.related.length?`<details><summary>関連問題</summary>${q.related.filter(id=>activeQuestionIds.has(id)).map(id=>`<button class="button secondary" style="margin-top:8px" data-action="start" data-id="${id}">${esc(question(id).title)} →</button>`).join('')}</details>`:''}</section>${a.topic?`<button class="button quiet" style="margin-top:14px" data-view="topics">分野の一覧に戻る</button>`:''}<div class="finish-actions"><button class="button secondary" data-action="end">今日はここまで</button>${state.session.intent==='direct'?`<button class="button primary" data-action="direct-return">${state.session.returnView==='flashcards'?'単語帳に戻る':state.session.returnView==='study'?'元の学習に戻る':'元の画面に戻る'}</button>`:`<button class="button primary" data-action="next" ${hasFreshTopicQuestion()?'':'disabled'}>${state.session.intent==='review'&&!hasFreshTopicQuestion()?'復習はここまで':'もう1問'}</button>`}</div>`;
}
function reviewHTML() {
  const list=reviewQuestions(); const paused=state.attempts.filter(a=>!complete(a)&&!continuedParents.has(a.id));
  return `<div class="page-heading"><h1>解き直し</h1></div><section class="panel"><h2>復習候補 <span class="badge">${list.length}問</span></h2>${list.length?list.map(({q,info})=>`<div><p class="page-note" style="margin-top:18px">${info.isDue?'復習日':'復習目安：'+(info.dueDate||dateText(info.due))}</p>${rowHTML(q,info,'review-start','解き直す')}</div>`).join(''):'<div class="empty"><p>復習候補はありません。</p><button class="button primary" data-action="start-session">とりあえずはじめる</button></div>'}</section>${paused.length?`<section class="panel"><h2>中断中</h2>${paused.slice().reverse().map(a=>`<div class="row"><div><p class="row-title">${esc(question(a.questionId).title)}</p><p class="row-meta">${timeText(a.updatedAt)} · ヒント ${a.hintCount}/${hintTotal(a)}</p></div><button class="button secondary" data-action="resume" data-id="${a.id}">続きから</button></div>`).join('')}</section>`:''}<details class="page-note"><summary>復習候補と日付</summary><p>不正解・ヒント利用・自信なし・復習日が来た問題を表示します。要復習なら翌日、自力正解なら3・7・14日後が目安です。計画のタイムゾーン（未登録なら資格の基準、応用情報は日本時間）で日付を判定します。先送りはこの端末の自動出題から外し、ここから再開できます。</p></details>`;
}
function historyHTML() {
  return `<div class="page-heading heading-row"><h1>学習記録</h1><span class="badge">${state.attempts.length}回</span></div>${motivationHTML()}<section class="panel record-tools"><div class="button-row"><button class="button secondary" data-view="topics">分野の記録</button><button class="button secondary" data-view="planning">受験日・計画</button><button class="button secondary" data-view="diagnostics">実力診断・結果</button><button class="button secondary" data-view="review">解き直し</button></div></section><section class="panel">${state.attempts.length?state.attempts.slice().reverse().map(a=>`<div class="row"><div><p class="row-title">${esc(question(a.questionId).title)} <span class="small muted">· 問${question(a.questionId).number}</span></p><p class="row-meta">${timeText(a.completedAt||a.updatedAt)}${a.contentRevision!=='original'?' · 編集した教材':''}${a.diagnosticRunId?' · 支援なし診断':a.topic?' · 分野別演習':''}${a.continuationOf?' · 中断から継続':''}</p>${a.readingNote?`<p class="row-meta">読んだ範囲：${esc(a.readingNote)}</p>`:''}<div class="history-result">${badge(a)} <span class="small muted">${complete(a)?'解答前の':''}ヒント ${a.hintsBeforeAnswer??a.hintCount}/${hintTotal(a)}${a.confidence?' · 自信なし':''}</span></div>${complete(a)&&a.hintCount>a.hintsBeforeAnswer?`<p class="row-meta">解答後にヒント ${a.hintCount-a.hintsBeforeAnswer}つを追加閲覧</p>`:''}</div><div class="row-actions"><button class="button secondary" data-action="resume" data-id="${a.id}">${complete(a)?'解説を見る':'続きから'}</button>${complete(a)&&activeQuestionIds.has(a.questionId)?`<button class="button quiet" data-action="start" data-id="${a.questionId}">解き直す</button>`:''}</div></div>`).join(''):'<div class="empty"><p>まだ学習記録はありません。</p><button class="button primary" data-action="start-session">とりあえずはじめる</button></div>'}</section><details class="page-note"><summary>記録の分類</summary><p>「自力で正解」は解答前にヒント・解答を見なかった正解です。解答後のヒント閲覧は別に記録します。</p></details>`;
}
function catalogMatches() {
  const words=catalog.query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  return base.filter(q=>(!catalog.year||String(q.year)===catalog.year)&&(!catalog.season||q.season===catalog.season)&&(!catalog.topic||q.topic===catalog.topic)&&(!catalog.enriched||enriched(question(q.id)))&&words.every(w=>`${q.title} ${q.topic} ${q.concept || ''} ${q.searchText || q.stem} ${q.year} ${q.number}`.toLocaleLowerCase().includes(w)));
}
function catalogRowsHTML() {
  const matches=catalogMatches(),pages=Math.max(1,Math.ceil(matches.length/PAGE_SIZE));catalog.page=Math.min(catalog.page,pages);
  const slice=matches.slice((catalog.page-1)*PAGE_SIZE,catalog.page*PAGE_SIZE);
  return `<div class="heading-row catalog-count"><p class="page-note" role="status">${matches.length}問${matches.length?` · ${(catalog.page-1)*PAGE_SIZE+1}〜${(catalog.page-1)*PAGE_SIZE+slice.length}問`:''}</p><button class="button quiet" data-action="reset-filters">絞り込みを解除</button></div>${slice.length?slice.map(q=>`<div class="row"><div><p class="row-title">${esc(q.title)}</p><p class="row-meta">${examLabel(q)} · 問${q.number} · ${esc(q.topic)}</p><p class="small muted">${Object.hasOwn(state.overrides,q.id)?'自分で編集した教材':enriched(q)?'個別ヒント・解説あり':'個別ヒント${q.hintCount??q.hints.length}段階 · 解説未追加'}</p>${latest(q.id)?badge(latest(q.id)):''}</div><div class="row-actions"><button class="button quiet" data-action="edit" data-id="${q.id}">教材を編集</button><button class="button secondary" data-action="start" data-id="${q.id}">解く</button></div></div>`).join(''):'<p class="empty">条件に合う問題はありません。</p>'}<div class="pagination"><button class="button secondary" data-action="catalog-page" data-page="${catalog.page-1}" ${catalog.page===1?'disabled':''}>前の20問</button><span>${catalog.page} / ${pages}</span><button class="button secondary" data-action="catalog-page" data-page="${catalog.page+1}" ${catalog.page===pages?'disabled':''}>次の20問</button></div>`;
}
function materialsHTML() {
  return `<div class="page-heading heading-row"><h1>問題と教材</h1><span class="badge">${base.length}問</span></div><section class="panel"><form class="catalog-filters" role="search" id="catalog-form"><label>年度<select name="year"><option value="">全年度</option>${[...new Set(base.map(q=>q.year).filter(Boolean))].sort((a,b)=>b-a).map(y=>`<option value="${y}" ${catalog.year===String(y)?'selected':''}>${y}年</option>`).join('')}</select></label><label>期<select name="season"><option value="">全て</option>${Object.entries(qualification.seasonLabels||{}).map(([value,label])=>`<option value="${esc(value)}" ${catalog.season===value?'selected':''}>${esc(label)}</option>`).join('')}</select></label><label>分野<select name="topic"><option value="">全分野</option>${topics().map(t=>`<option ${catalog.topic===t?'selected':''}>${esc(t)}</option>`).join('')}</select></label><label class="catalog-search">キーワード<input type="search" name="query" value="${esc(catalog.query)}" placeholder="例：DNS、キャッシュ"></label><label class="confidence catalog-enriched"><input type="checkbox" name="enriched" ${catalog.enriched?'checked':''}>個別解説あり</label></form><div id="catalog-results">${catalogRowsHTML()}</div></section><section class="panel"><button class="button secondary" data-action="export-materials">教材を書き出す</button><details><summary>教材の出典と編集範囲</summary><p>${esc(qualification.sourceDescription)}</p><p>全${base.length}問に問題別の段階ヒントがあります。詳しい個別解説は${base.filter(q=>enriched(q)).length}問に追加済みです。自分用のヒントや解説も保存できます。</p><p>キーワード検索には自動読み取りのテキストを使います。読み取り誤りがあるため、問題の内容は原本画像で確認してください。</p><a href="${esc(qualification.sourceDoc)}">詳しい出典と利用条件</a></details></section>`;
}
function sourceImagesHTML(q) {
  return `<div class="source-question">${q.sourceImages.map((src,i)=>`<figure><button type="button" class="source-image-button image-zoom-target" data-action="zoom" data-id="${q.id}" data-image="${i}" aria-label="問題画像を拡大"><img src="${src}" alt="${esc(q.source)}の原本画像${q.sourceImages.length>1?'（'+(i+1)+'/'+q.sourceImages.length+'）':''}" width="${q.imageSizes[i].width}" height="${q.imageSizes[i].height}" decoding="async">${imageZoomCue}</button></figure>`).join('')}</div>`;
}
 return {homeHTML, topicsHTML, studyHTML, reviewHTML, historyHTML, materialsHTML, catalogRowsHTML};
}
