import {validateCardEvents} from '../domain/flashcards.js';
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||new Error('単語帳を保存できません。'));tx.onerror=()=>{};});
export function createCardStore({rootPath,owner,qualificationId}){
 const scope=[owner,qualificationId];let connection,queue=Promise.resolve();
 async function db(){if(!connection)connection=new Promise((resolve,reject)=>{const r=indexedDB.open(`hitomon:${rootPath}:cards`,1);r.onupgradeneeded=()=>{const events=r.result.createObjectStore('events',{keyPath:['owner','qualificationId','id']});events.createIndex('namespace',['owner','qualificationId']);r.result.createObjectStore('checkpoints',{keyPath:['owner','qualificationId']});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return connection;}
 async function read(){await queue.catch(()=>{});const database=await db(),tx=database.transaction(['events','checkpoints']),finished=done(tx);const [events,checkpoint]=await Promise.all([request(tx.objectStore('events').index('namespace').getAll(scope)),request(tx.objectStore('checkpoints').get(scope))]);await finished;return {events:validateCardEvents(events.map(({owner,qualificationId,...e})=>e)),checkpoint:checkpoint?.value||null};}
 function write(checkpoint,event=null){const operation=queue.then(async()=>{if(event)validateCardEvents([event]);const database=await db(),tx=database.transaction(['events','checkpoints'],'readwrite'),finished=done(tx);try{if(event){const store=tx.objectStore('events');const count=await request(store.index('namespace').count(scope));if(count>=20000)throw new Error('単語帳の記録が2万件に達しました。');store.add({...event,owner,qualificationId});}tx.objectStore('checkpoints').put({owner,qualificationId,value:checkpoint});}catch(error){tx.abort();await finished.catch(()=>{});throw error;}await finished;});queue=operation.catch(()=>{});return operation;}
 function importEvents(events){validateCardEvents(events);const operation=queue.then(async()=>{const database=await db(),tx=database.transaction('events','readwrite'),finished=done(tx),store=tx.objectStore('events');try{let count=await request(store.index('namespace').count(scope));for(const e of events){const old=await request(store.get([...scope,e.id]));if(old){const {owner,qualificationId,...value}=old;if(['id','cardId','cardVersion','outcome','at'].some(k=>value[k]!==e[k]))throw new Error('同じIDの異なる記録があります。現在の記録は変更していません。');}else {if(++count>20000)throw new Error('取り込み後の単語帳の記録が2万件を超えます。');store.add({...e,owner,qualificationId});}}}catch(error){tx.abort();await finished.catch(()=>{});throw error;}await finished;});queue=operation.catch(()=>{});return operation;}
 function clear(){const operation=queue.then(async()=>{const database=await db(),tx=database.transaction(['events','checkpoints'],'readwrite'),finished=done(tx);const index=tx.objectStore('events').index('namespace');const rows=await request(index.getAllKeys(scope));for(const key of rows)tx.objectStore('events').delete(key);tx.objectStore('checkpoints').delete(scope);await finished;});queue=operation.catch(()=>{});return operation;}
 return {read,write,importEvents,clear,close:async()=>{await queue;if(connection)(await connection).close();}};
}
